<style>
  .modal-body {
    max-height: 550px;
    overflow-y: auto;
    text-align: justify;
}
</style>
<!-- refund Modal -->
<div class="modal fade" id="minor_inter" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="new-heading mb-0">Minor & User Interaction - Code of Conduct Guidelines</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h4 class="modal-heading2">Table of contents:</h4>
        <ul>
          <li><a href="#minor_inter_definition">A. Definitions</a></li>
          <li><a href="#minor_inter_rules">B. Rules of Conduct</a></li>
          <li><a href="#minor_inter_child">C. Child Abuse and Punishments</a></li>
          <li><a href="#minor_inter_reporting">D. Reporting</a></li>
        </ul>
         
        <p class="modal-para">(the <b>“Company”</b>) owns and operates the website <a href="http://www.utsavlife.com">www.utsavlife.com</a> and mobile application (together <b>“Utsavlife Platform”</b> or <b>“Utsavlife”</b>). Utsavlife Platform is an online Service provider platform that supports and facilitates the online creation of Booking services by the users who wish to be book the required services on Utsavlife Platform. 
          Considering the possible interactions between the User (who may be minors i.e., under the age of 18 years) and you, the Company realizes the need to implement specific guidelines that govern your conduct on the Utsavlife Platform while interacting with Users (including Minors). Protecting the safety and well-being of children is of utmost importance to the Company and hence the Company has adopted this Minor Interaction - Code of Conduct Guidelines <b>(“Minor & User Interaction Guidelines'')</b> requiring  users to conduct themselves with utmost care while interacting with minors on the Utsavlife Platform and take reasonable measures to ensure the safety of such minors.
          This Minor & User of Utsavlife Platform Interaction Guidelines aims to define and lay down the expectations on behaviour and your actions while interacting with minors on Utsavlife. Additionally, it will lay down the scope of application of this Minor & User Interaction Guidelines and guidelines for reporting any issues relating to minors.
          </p>
        <p class="modal-para">Please read this Minor & User Interaction Guidelines, along with the Privacy Policy, Terms and Conditions, User Guidelines, and all terms and conditions, rules and policies made available or published on Utsavlife Platform as they shall govern your use of the Utsavlife Platform. By using or visiting the Utsavlife Platform or any Utsavlife software, data feeds, and service provided to you on, from, or through the Utsavlife Platform, you signify your agreement to (1) this Minor & User Interaction Guidelines; (ii) the “Terms and Conditions'', (3) Utsavlife’s Privacy Policy and any other terms that are updated and uploaded on the Utsavlife Platform from time to time. If you do not agree to any of these terms, please do not use the Utsavlife Platform.</p>
        <h4 class="modal-heading" id="minor_inter_definition">A. Definitions</h4>
        <p class="modal-para">1. <b> “Users”</b> shall mean and include all users (including Minors) who have to using Utsavlife as an online service providing platform.</p>
        <p class="modal-para">2. <b>“Minor/s” or “Child/Children”</b> shall mean and be construed in accordance with the Indian Majority Act, 1875, the Protection of Children against Sexual Offences Act, 2012 (POCSO Act, 2012), Child Labour (Prohibition and Regulation) Act, 1986 and such other applicable Indian laws i.e., the term shall mean and include all individuals who have not attained the age of 18 (eighteen) years.</p>
        <p class="modal-para">3. <b>“Minor & User Interaction Guidelines”</b> shall mean this Minor & User Interaction - Code of Conduct Guidelines, on Utsavlife platform and includes all annexures and appendices attached thereto, if any and updates, changes and amendment as may be made by the Company and uploaded herein, from time to time.</p>
        <h4 class="modal-heading" id="minor_inter_rules">B. Rules of Conduct</h4>
        <p class="modal-para">1. <b>No Discrimination:</b>  Treat every Minor with empathy and respect, regardless of his/her race, colour, gender, sexuality, language, religion, religious belief, heritage, political/other opinion, national/ethnic/social origin or property/disability/birth/other status; listen to them and respect their views.</p>
        <p class="modal-para">2. <b>Appropriate Communication and Behaviour:</b> Good communication is the vehicle for using and essential for further development of Minor. Good communication involves listening and talking in ways that Minors understand and feel heard, important and valued. Using any form of language or behaviour towards Minor that is inappropriate, demotivating, harassing, abusive, sexually provocative, demeaning, intimidating, offensive, discriminatory or culturally insensitive shall not be tolerated; further, any communication or behaviour while interacting with Minor shall not, in any manner whatsoever, induce or support physical or sexual relationships with Minor or portray use of or encourage the use of alcohol, drugs, cigarettes or other intoxicating or restricted substances. While agreed that individuals have the right to voice their opinions, the Company has zero tolerance towards any form of communication or behaviour stated hereinabove, and the Company –</p>
        <p class="modal-para">a. <b>DOES NOT</b> encourage or tolerate any form of hate speech or statements that are libellous, slanderous, threatening, violent, predatory, defamatory, or any statement that incites hatred against specific individuals or groups with respect to but not limited to race or ethnic origin, country caste, religion, disability, gender, age, sexual orientation/gender identity etc.; and</p>
        <p class="modal-para">b. <b>DOES NOT</b> tolerate any form of harassment or bullying on the Utsavlife Platform and strive to keep the platform a safe space to foster Using. Harassment in this case would include, without limitation, abusive videos, comments, messages, revealing someone’s personal information, including sensitive personally identifiable information of individuals, content or comments uploaded in order to humiliate someone, sexual harassment or sexual bullying in any form.</p>
        <p class="modal-para">If it comes to the notice of the Company that your actions towards a Minor are inappropriate in any manner, then the Company reserves the right to take immediate and necessary actions, as it deems fit including legal proceeding, against you.</p>
        <p class="modal-para">3. <b>Content Sharing:</b> Your interaction with a Minor on Utsavlife should be specific to the purpose of your engagement with such Minor and accordingly, information shared with such Minor should be strictly applicable and relatable to the subject-matter being discussed between you and the Minor. Sharing and display of inappropriate content with/to the Minor including but not limited to materials encouraging crime, violence, terrorism, racism, sexism, self-harm, suicide, cruelty, pornography, gambling, or any content whose sole objective is to sensationalize, shock or disturb individuals (electronically or in any other form) is not allowed and shall not be tolerated.</p>
        <p class="modal-para">4. <b>Confidentiality:</b> Company understands that during the interactions between you and the User (including Minors), you may be privy to certain personal information about User (including Minors) or their parents/guardians. Hence, you shall at all times maintain the confidentiality of such information received and ensure that such information is dispensed to only those individuals who are legitimately entitled to strictly in accordance with their agreement with the Company and Utsavlife’s terms and condition and policies (including its Privacy Policy) as available on Company’s website.</p>
        <h4 class="modal-heading" id="minor_inter_child">C. Child Abuse and Punishments</h4>
        <p class="modal-para">Apart from the prohibited activities stated in the ‘Rules of Conduct’ section above, it is important for you to understand that Child abuse in any form (physical, emotional, or sexual) and in any manner (including through online platforms) could be punishable under the Indian Laws and you are strictly prohibited from engaging in such activities in any manner whatsoever.</p>
        <p class="modal-para"><b>1. What Constitutes Child Abuse?</b></p>
        <p class="modal-para">Child abuse or maltreatment constitutes all forms of physical and/or emotional ill-treatment, sexual abuse, neglect or negligent treatment or commercial or other exploitation, resulting in actual or potential harm to the child’s health, survival, development or dignity in the context of a relationship of responsibility, trust or power.</p>
        <p class="modal-para">i. <b>Physical abuse:</b> The intentional use of physical force against a child that results in or has a high likelihood of resulting in harm to the child’s health, survival, development or dignity. This includes hitting, beating, kicking, shaking, biting, strangling, scalding, burning, poisoning and suffocating.</p>
        <p class="modal-para">ii. <b>Emotional/mental abuse:</b> Emotional abuse includes the failure to provide a developmentally appropriate, supportive environment, so that the Child can develop a stable and full range of emotional and social competencies proportionate with his or her personal potential and in the context of the society in which the Child dwells. <b>Acts include restriction of movement, patterns of belittling, denigrating, scapegoating, threatening, scaring, discriminating, ridiculing or other non-physical forms of hostile or rejecting treatment</b></p>
        <p class="modal-para">iii. <b>Neglect and negligent treatment​:</b> Neglect is the failure on the part of the parents, guardian, or other responsible party to provide for the Child’s basic needs, such as food, shelter, medical care, educational opportunities, or protection and supervision. <b>It is abuse through omission of the necessary environment and resources for the Child to reach their full potential; and the act of not recognizing physical or emotional abuse.</b></p>
        <p class="modal-para">iv. <b>Exploitation:</b> Commercial or other exploitation of a Child refers to use of the Child in work or other activities for the benefit of others. This includes, but is not limited to, Child labour and Child prostitution. These activities are to the detriment of the Child’s physical or mental health, education, or spiritual, moral or social-emotional development. The Child Labour (prohibition and regulation) Act, 1986 and the Protection of Children from Sexual Offences Act, 2012 address the issues concerning Child labour and sexual abuse, and any act under in relation to that is deemed a punishable offence under the said regulations.</p>
        <p class="modal-para">v. <b>Sexual abuse​:</b> Sexual abuse is an act or behaviour which constitutes a sexual offence under the Protection of Children from Sexual Offences Act, 2012 (‘POCSO Act, 2012’), as amended from time to time. Such sexual offences include penetrative sexual assault (including rape), non-penetrative sexual assault (including touching the private parts of a Child), sexual harassment (including stalking a Child, showing a Child pornography, online grooming, and making a Child exhibit his/her body) and using a Child for pornographic purposes (including storing of pornographic material involving a Child for commercial purposes).</p>
        <p class="modal-para">An abetment of and even an attempt to commit a sexual offence under the POCSO Act, 2012 are also considered to be offences. Certain offences under the POCSO, 2012 are considered to be aggravated offences and are subject to stringent punishments.</p>
        <p class="modal-para">2. <b>Legal Implications of Online Child Abuse:</b> <br>
          This Minor and User Interaction Guidelines has only highlighted a few circumstances of Child Abuse and the legal implications thereto with an intention to give you a brief insight on the probable consequences of mis-utilizing the Utsavlife Platform. Hence, you must not consider the information provided in this Minor and User Interaction Guidelines as the ultimate source of information relating to Child Abuse and its legal implications. It is strongly recommended that they keep themselves updated about the applicable laws and regulations from time-to-time.
          </p>
        <p class="modal-para">a. <b>Juvenile Justice (Care and Protection of Children) Act, 2015:</b> It is to be noted that the Juvenile Justice (Care and Protection of Children) Act, 2015 criminalizes acts that may cause a child mental or physical suffering. As per section 75 of the Act, whoever, having the actual charge of, or control over, a Child, assaults, abandons, abuses, exposes or will fully neglects the Child or causes or procures the Child to be assaulted, abandoned, abused, exposed or neglected in a manner likely to cause such Child unnecessary mental or physical suffering, shall be punishable with imprisonment for a term which may extend to three years or with fine of one lakh rupees or with both.</p>
        <p class="modal-para">b. <b>Sexual Harassment:</b> POCSO Act, 2012 recognizes sexual harassment as a punishable offence; ‘Sexual Harassment’ as per Section 11 of the POCSO Act, 2012 is any act of a person done/committed with a sexual intent and such acts include –</p>
        <p class="modal-para">i. Uttering of any word or making sounds, or gestures or exhibiting any object or part of body with the intention that such word or sound shall be heard, or such gesture or object or part of body shall be seen by the Child; or</p>
        <p class="modal-para">ii. making a Child exhibit his/her body or any part of his/her body so as it is seen by such person or any other person; or showing any object to a Child in any form or media for pornographic purposes; or</p>
        <p class="modal-para">iii. repeatedly or constantly following or watching or contacting a Child either directly or through electronic, digital or any other means; or</p>
        <p class="modal-para">iv. threatening to use, in any form of media, a real or fabricated depiction through electronic, film or digital or any other mode, of any part of the body of the Child or the involvement of the child in a sexual act; or</p>
        <p class="modal-para">v. enticing a child for pornographic purposes or gives gratification therefore.</p>
        <p class="modal-para">Section 12 of the POCSO Act, 2012 states that an act of sexual harassment upon a Child shall be punished with either imprisonment for a term up to three years or fine or both.</p>
        <p class="modal-para"><b>b. Voyeurism and violation of privacy:</b></p>
        <p class="modal-para">i. Section 354C, the Indian Penal Code (IPC) 1860 states that viewing and/or capturing the image of a girl or woman going about her private acts, where she thinks that no one is watching her, is a crime. The offender in such cases of voyeurism can be punished with three to seven years of imprisonment and a fine. While this section of the IPC can only be used by girls and women, the Information Technology Act, 2000 is gender neutral.</p>
        <p class="modal-para">ii. Section 66E, IT Act, 2000: Intentionally or knowingly capturing, publishing or transmitting the image of a private area of any person without his or her consent, under circumstances violating the privacy of that person, shall be punished with imprisonment which may extend to three years or with fine not exceeding Rupees two lakh or with both.</p>
        <p class="modal-para"><b>c. Sending obscene material without the consent of the recipient:</b></p>
        <p class="modal-para">i. Section 67, IT Act, 2000: It punishes sharing obscene material in electronic form. The punishment can be jail for five years and a fine of Rs 10 lakhs.</p>
        <p class="modal-para">ii. Section 67A, IT Act, 2000: It punishes sharing material containing sexually explicit acts in electronic form with jail for seven years and a fine of Rs 10 lakhs.</p>
        <p class="modal-para">The provisions of the Information Technology Act are not gender specific and apply to everyone.</p>
        <h4 class="modal-heading" id="minor_inter_reporting">D. Reporting</h4>
        <p class="modal-para">While it is important that you do not commit or cause to commit an act prohibited under this Minor and User Interaction Guidelines and any applicable laws relating to Child Abuse, it is also very important that they do not remain bystanders when they encounter online abuse and exploitation. In fact, being aware of a child abuse case and not reporting it is illegal under the POCSO Act, 2012.</p>
        <p class="modal-para">In the event the you suspect any form Child Abuse from your interaction with the Minor User, then you must write to <a href="mailto:info@utsavlife.com">info@utsavlife.com</a>, so that the necessary actions can be taken by the Company.</p>
        <p class="modal-para"></p>
      </div>
    </div>
  </div>
</div>