<style>
  .modal-body {
    max-height: 550px;
    overflow-y: auto;
    text-align: justify;
    overflow-x: hidden;
}
</style>
<!-- privacy Modal -->
<div class="modal fade" id="privacy" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="new-heading mb-0">Privacy Policy</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h4 class="modal-heading">Utsavlife Privacy Policy</h4> 
        <h4 class="modal-heading2">Table of contents:</h4>
        <ul>
          <li><a href="#general">A. General Privacy Terms</a></li>
          <li><a href="#applicability">B. Applicability</a></li>
          <li><a href="#access">C. Access</a></li>
          <li><a href="#use_of_platform">D. Use of the Platform/Services by Children</a></li>
          <li><a href="#controllers">E. Controllers</a></li>
          <li><a href="#personal_information">F. Personal Information</a></li>
          <li><a href="#info_collect">G. Information We Collect</a></li>
          <li><a href="#basis_of_collection">H. Basis of Collection and Processing of Your Personal Information</a></li>
          <li><a href="#use_share_info">I. How we Use and Share the Information Collected</a></li>
          <li><a href="#cross_border_data">J. Cross-Border Data Transfer</a></li>
          <li><a href="#duration_info">K. Duration for which your Information is Stored</a></li>
          <li><a href="#your_choice">L. Your Choices</a></li>
          <li><a href="#your_rights">M. Your Rights</a></li>
          <li><a href="#info_sec">N. Information Security</a></li>
          <li><a href="#personal_comm">O. Promotional Communications</a></li>
          <li><a href="#interest_based_ads">P. Interest-Based Ads</a></li>
          <li><a href="#mod-privacy-policy">Q. Modification to Privacy Policy</a></li>
          <li><a href="#grievances">R. Privacy Grievances</a></li>
        </ul>
        <h4 class="modal-heading" id="general">A. General</h4> 
        <p class="modal-para">In addition to our <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and conditions</a> Service, Utsavlife respects your privacy and is committed to protecting it. This Privacy Policy (the “Policy”) explains the types of information collected by Utsavlife when you use the Platform (as defined in <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and conditions</a>) that references this Policy, how we collect, use, share and store such information collected and also explains the rationale for collection of such information, the privacy rights and choices you have regarding your information submitted to us when you use the Services.</p>
        <p class="modal-para">For ease of reference, use of the terms “Utsavlife”, “we”, “us, and/or “our” refer to SRV Technology – a company incorporated in India and all of its affiliates which have license to host the Platform and offer Services. Similarly, use of the terms “you”, “yours” and/or “User(s)” refer to all users of the Platform and includes all customers and Content Providers (as more particularly defined under our <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and conditions</a>).</p>
        <p class="modal-para">The Services are governed by this Policy, <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and conditions</a>, and any other rules, policies or guidelines published on the Platform as applicable to you. Please read this Policy carefully prior to accessing our Platform and using the Services. By accessing and using the Platform, providing your Personal Information (defined below), or by otherwise signalling your agreement when the option is presented to you, you consent to the collection, use, disclosure, sharing and storing of information described in this Policy, Terms of Service and any other rules, policies or guidelines published on the Platform as applicable to you (collectively referred to as the “Platform Terms''), and Utsavlife disclaims all the liabilities arising therefrom. If you have inadvertently submitted any Personal Information to Utsavlife prior to reading this Policy statements set out herein, or you do not agree with the way your Personal Information is collected, stored, or used, then you may access, modify and/or delete your Personal Information in accordance with this Policy (refer to the sections about Your Choices and Your Rights).</p>
        <p class="modal-para">If any information you have provided or uploaded on the Platform violates the Platform Terms, Utsavlife may be required to delete such information upon informing you of the same and revoke your access to the Platform if required.</p>
        <p class="modal-para">Capitalized terms used but not defined in this Policy can be found in our <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and conditions</a></p>
        <p class="modal-para">If you have any questions about this Policy, please contact us at <a href="mailto:info@utsavlife.com">info@utsavlife.com</a></p>
        <h4 class="modal-heading" id="applicability">B. Applicability</h4> 
        <p class="modal-para">This Policy applies to all Users of the Platform.</p>
        <p class="modal-para">Utsavlife owns and/or manages several platforms (other than the Platform) that offer a range of services including services related to technology solutions in the space of e-service, either by itself or through its affiliates and subsidiaries (“Utsavlife Group Platforms”). Each of the Utsavlife Group Platforms have published their own privacy policies. Accordingly, this Policy does not apply to information collected through the Utsavlife Group Platforms and only applies to the collection of your information through the Platform. Please visit the relevant Utsavlife Group Platform to know the privacy practices undertaken by them.</p>
        <p class="modal-para">Utsavlife has taken reasonable precautions as per applicable laws and implemented industry standards to treat Personal Information as confidential and to protect it from unauthorized access, improper use or disclosure, modification and unlawful destruction or accidental loss of the Personal Information.</p>
        <h4 class="modal-heading" id="access">C. Access</h4>
        <p class="modal-para">You may be allowed to access and view the Platform as a guest and without creating an account on the Platform or providing any Personal Information; Utsavlife does not validate or takes no responsibility towards information, if any, provided by you as a guest, except as otherwise required under any law, regulation, or an order of competent authority. However, to have access to all the features and benefits on our Platform, you are required to first create an account on our Platform. To create an account, you are required to provide certain Personal Information as may be required during the time of registration and all other information requested on the registration page, including the ability to receive promotional offers from Utsavlife, is optional. Utsavlife may, in future, include other optional requests for information from you to help Utsavlife to customize the Platform to deliver personalized information to you. Utsavlife may keep records of telephone calls or emails received from or made by you for making enquiries, feedback, or other purposes for the purpose of rendering Services effectively and efficiently.</p>
        <h4 class="modal-heading" id="use_of_platform">D. Use of the Platform/Services by Children</h4>
        <p class="modal-para">As stated in our <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and conditions</a>, to register on the Platform you must meet the ‘Age Requirements’ (as defined in our <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and conditions</a>). If you are a “Minor” or “Child” i.e., an individual who does not meet the Age Requirements, then you may not register on the Platform, and only your Parent (defined below) can register on the Platform on your behalf, agree to all Platform Terms and enable access to you under their guidance and supervision.</p>
        <p class="modal-para">While some of our Services may require collection of a Child’s Personal Information, we do not knowingly collect such Personal Information from a Child and assume that information has been provided with consent of the Parent. If you are a Parent and you are aware that your Child has provided us with any Personal Information without your consent, please contact us at <a href="mailto:info@utsavlife.com">info@utsavlife.com</a> If we become aware that we have collected Personal Information from a Child in the absence of consent of the Parent, we will take steps to remove such information from our servers.</p>
        <p class="modal-para">The information in the relevant parts of this notice applies to Children as well as adults. If your Child faces any form of abuse or harassment while availing our Services, you must write to us at <a href="mailto:info@utsavlife.com">info@utsavlife.com</a>, so that necessary actions could be considered.</p>
        <h4 class="modal-heading" id="controllers">E. Controllers</h4>
        <p class="modal-para">Utsavlife is the controller of Personal Information that it collects and processes in connection with the use of the Platform and the provision of the Services on the Platform. The kind of Personal Information we collect in connection with such use is detailed below.
        </p>
        <h4 class="modal-heading" id="personal_information">F. Personal Information</h4>
        <p class="modal-para">“Personal Information” shall mean the information which identifies a User i.e., first and last name, identification number, email address, age, gender, location, photograph and/or phone number provided at the time of registration or any time thereafter on the Platform.</p>
        <p class="modal-para">“Sensitive Personal Information” shall include (i) passwords and financial data (except the truncated last four digits of credit/debit card), (ii) health data, (iii) official identifier (such as biometric data, aadhar number, social security number, driver’s license, passport, etc.,), (iv) information about sexual life, sexual identifier, race, ethnicity, political or religious belief or affiliation, (v) account details and passwords, or (vi) other data/information categorized as ‘sensitive personal data’ or ‘special categories of data’ under the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011, General Data Protection Regulation (GDPR) and / or the California Consumer Privacy Act (CCPA) (“Data Protection Laws”) and in context of this Policy or other equivalent / similar legislations.</p>
        <p class="modal-para">Usage of the term ‘Personal Information’ shall include ‘Sensitive Personal Information’ as may be applicable to the context of its usage.</p>
        <p class="modal-para">We request you to not provide Utsavlife with any Personal Information unless specifically requested by us. In the event you share with Utsavlife any Personal Information without us having specifically requested for the same, then we bear no liability in respect of such Personal Information provided by you.</p>
        <h4 class="modal-heading" id="info_collect">G. Information We Collect</h4>
        <p class="modal-para">We only collect information about you if we have a reason to do so — for example, to provide our Services on the Platform, to communicate with you, or to make our Services better.</p>
        <p class="modal-para">We collect this information from the following sources:</p>
        <h4 class="modal-heading2">Information we collect from You:</h4>
        <p class="modal-para"><b>Basic account information:</b> In order to access certain features of the Platform, you will need to create an account and register with us. We ask for basic information which may include your name, an email address, state of residence, and password, along with a username and phone/mobile number.</p>
        <p class="modal-para"><b>Know Your Customer ('KYC') information:</b> If you are a service Provider registered with us, then, we also collect the KYC information, which may include information pertaining to your PAN number, aadhaar number, driver’s license, passport, your entity details such as name, MOU/AOA, certificate of incorporation, list of directors/partners, social security number etc., along with the relevant documents. We collect this information and documents from you to complete our verification process including pursuant to any other arrangement / agreement executed with you.</p>
        <p class="modal-para"><b>Public profile information:</b> If you are a service Provider, we may also collect certain additional information from you to enable creation of your public profile, if any, on the Platform to help Customers and other Users know you better. We do not share your KYC information, documents or any such Personal Information on these public profiles. Your public profile will only contain Personal Information that are required for Customers or Users to know you (as applicable) viz., your username, a brief description of any service you have made available on the Platform, your photo, and such similar information that may enable a customer or other User to know you better. The information in your public profile will be based on the information you provide to us or as updated by you on such applicable sections.</p>
        <p class="modal-para"><b>Information when you communicate with us:</b> When you write to us with a question or to ask for help, we will keep that correspondence, and the email address, for future reference; this may also include any phone/ mobile numbers if you have provided us the same as part of your communication either in writing (emails included), over a phone call or otherwise. When you browse pages on our Platform, we will track that for statistical purposes which may be to improve the Platform and the Services. You may also provide us your Personal Information or other information when you respond to surveys, enter any form of contests, tests, events, competitions, webinars, etc., hosted by Utsavlife, either on the Platform or otherwise, or when you otherwise communicate with us via form, e-form, email, phone, or otherwise, we store a copy of our communications (including any call recordings or emails, if any, as permitted by applicable law).</p>
        <p class="modal-para"><b>Information related to location:</b> You may also choose to provide location related information, including but not limited to access to GPS, which will enable us, with your consent, to offer customized offerings for specific services where location data is relevant and/or applicable such as informing you whether services on the Platform that you have expressed interest in may be availed of at or near your location.</p>
        <h4 class="modal-heading2">Information we collect automatically:</h4>
        <p class="modal-para"><b>Device and Log information:</b> When you access our Platform, we collect information that web browsers, mobile devices, and servers typically make available, including the browser type, IP address, unique device identifiers, language preference, referring site, the date and time of access, operating system, and mobile network information. We collect log information when you use our Platform — for example, when you create or make changes to your account information on the Platform.</p>
        <p class="modal-para"><b>Usage information:</b> We collect information about your usage of our Platform. We also collect information about what happens when you use our Platform (e.g., page views, support document searches, features enabled for your account, interactions with other parts of our Services) along with information about your Supported Device (e.g., screen size, name of cellular network, and mobile device manufacturer). We use this information to provide our Platform to you, get insights on how people use our Platform so that we can make our Platform better, and understand and make predictions about User retention.</p>
        <p class="modal-para"><b>Location information:</b> We may determine the approximate location of your Supported Device from your Internet Protocol (IP) address. We may collect and use this information to calculate how many people visit from certain geographic regions or to improve our Platform Services.</p>
        <p class="modal-para"><b>Information from cookies & other technologies:</b> We may collect information about you through the use of cookies and other similar technologies. A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. For more information on our use of cookies and similar technologies, please refer to our <a href="#" data-bs-toggle="modal" data-bs-target="#contact" data-bs-dismiss="modal">Cookie Policy.</a></p>
        <h4 class="modal-heading2">Information we collect from other sources:</h4>
        <p class="modal-para">We might receive and collect information about you from other sources in the course of their services to us or from publicly available sources, as permitted by law, which we may combine with other information we receive from or about you. For example, we may receive information about you from a social media site or a Google service if you connect to the Services through that site or if you use the Google sign-in.</p>
        <h4 class="modal-heading" id="basis_of_collection">H. Basis of Collection and Processing of Your Personal Information</h4>
        <h4 class="modal-heading2">Basis for collection:</h4>
        <p class="modal-para">We collect and process your Personal Information based on the following legal parameters depending upon the nature of Personal Information and the purposes for which it is processed:</p>
        <p class="modal-para"><b>Consent:</b> We rely on your consent to process your Personal Information in certain situations. If we require your consent to collect and process certain Personal Information, as per the requirements under the applicable Data Protection Laws, your consent is sought at the time of collection of your Personal Information and such processing will be performed where consent is secured.</p>
        <p class="modal-para"><b>Compliance with a legal obligation:</b> Your Personal Information may be processed by us, to the extent that such processing is necessary to comply with a legal obligation.</p>
        <h4 class="modal-heading2">Processing of your Personal Information:</h4>
        <p class="modal-para">We may process your Personal Information in connection with any of the purposes and uses set out in this Policy on one or more of the following legal grounds:</p>
        <p class="modal-para">Because it is necessary to perform the Services you have requested or to comply with your instructions or other contractual obligations between you and us;</p>
        <p class="modal-para">To comply with our legal obligations as well as to keep records of our compliance processes;</p>
        <p class="modal-para">Because our legitimate interests, or those of a third-party recipient of your Personal Information, make the processing necessary, provided those interests are not overridden by your interests or fundamental rights and freedoms;</p>
        <p class="modal-para">Because you have chosen to publish or display your Personal Information on a public area of the Platform, such as a comment area;</p>
        <p class="modal-para">Because it is necessary to protect your vital interests;</p>
        <p class="modal-para">Because it is necessary in the public interest; or</p>
        <p class="modal-para">Because you have expressly given us your consent to process your Personal Information in a particular manner.</p>
        <p class="modal-para">We do not use Personal Information for making any automated decisions affecting or creating profiles other than what is described in this Policy.</p>
        <p class="modal-para">Where the processing of your Personal Information is based on your consent, you have the right to withdraw your consent at any point in time in accordance with this Policy. Please note that should the withdrawal of consent result in us not being able to continue offering our Services to you, we reserve the right to withdraw or cease from offering our Services to you upon your consent withdrawal. You may withdraw consent by contacting us with a written request to the contact details provided in the <a href="#grievances">‘Grievances’</a> section below. Upon receipt of your request to withdraw your consent, the consequences of withdrawal may be communicated to you. Upon your agreement to the same, your request for withdrawal will be processed.</p>
        <h4 class="modal-heading" id="use_share_info">I. How we Use and Share the Information Collected</h4>
        <h4 class="modal-heading2">We use/process your information in the following manner:</h4>
        <p class="modal-para"><b>To provide Services on our Platform:</b>We use your information as collected by us to allow you to access the Platform and the Services offered therein, including without limitation to set-up and maintain your account, provide customer service, fulfil purchases through the Platform, verify User information and to resolve any glitches with our Platform. The legal basis for this processing is consent or, where applicable, our legitimate interests in the proper administration of our Platform, and/or the performance of a contract between you and us.
        <p class="modal-para"><b>To improve our Platform and maintain safety:</b>We use your information to improve and customize the Platform and Services offered by us, including providing automatic updates to newer versions of our Platform and creating new features based on the Platform usage analysis. Further, we also use your information to prevent, detect, investigate, and take measures against criminal activity, fraud, misuse of or damage to our Platform or network, and other threats and violations to Utsavlife’s or a third party's rights and property, or the safety of Utsavlife, its users, or others. The legal basis for this processing is consent or, where applicable, our legitimate interests in the proper administration of our Platform, and/or the performance of a contract between you and us.</p></p>
        <p class="modal-para"><b>To market our Platform and communicate with You:</b> We will use your information to develop a more targeted marketing of our Platform, to communicate with you about our offers, new products, services or even receive your feedback on the Platform. The legal basis for this processing is consent or, where applicable, our legitimate interests in the proper administration of our Platform, and/or the performance of a contract between you and us.</p>
        <p class="modal-para"><b>To establish, exercise, or defend legal claims:</b> We may process any Personal Information identified in this Policy when necessary for establishing, exercising, or defending legal claims, whether in court, administrative, or other proceedings. The legal basis for this processing is our legitimate interest in the protection and assertion of our legal rights, your legal rights, and the legal rights of others.</p>
        <p class="modal-para"><b>To manage risk and obtain professional advice:</b> We may process any of the Personal Information identified in this Policy to manage risk or obtain professional advice. The legal basis for this processing is our legitimate interest in the proper protection of our business and Platform</p>
        <p class="modal-para"><b>Consent:</b> We may otherwise use your information with your consent or at your direction.</p>
        <p class="modal-para"><b>To Better Understand Our Users:</b> We may use information we gather to determine which areas of the Services are most frequently visited to understand how to enhance the Services.</p>
        <p class="modal-para">We share the information collected as per terms of this Policy only in the manner specified hereinbelow. We do not sell or otherwise disclose Personal Information we collect about you for monetary or other valuable consideration. Further, only authorized representatives of Utsavlife and on a need-to-know basis use any information received from you and as consented by you. In the event of any identified unauthorized use or disclosure of information or upon your complaint as stated under the <a href="#grievances">‘Grievances’</a> section below, we will investigate any such complaint and take the appropriate action as per the applicable Data Protection Laws.</p>
        <p class="modal-para"><b>Affiliates and Subsidiaries:</b> We may disclose information about you to our affiliates, subsidiaries and other businesses under the same control and ownership, and their respective officers, directors, employees, accountants, attorneys, or agents, who need the information to help us provide the Services or process the information on our behalf. We require our affiliate, subsidiaries and other businesses under the same control and ownership to follow this Privacy Policy for any Personal Information that we share with them. Further, if you have availed any Service that is offered by Utsavlife in collaboration with one or more Utsavlife Group Platforms, then we may share your Personal Information with the relevant Utsavlife Group Platform, who may also communicate with you regarding certain other products/services offered by them separately via email, phone, SMS and/or such other mode of communication; you will always have an option to opt out of receiving some or all of such promotional communications from an Utsavlife Group Platform through the unsubscribe link in the email or such other option that may be communicated to you.</p>
        <p class="modal-para"><b>Third-party vendors/service providers including integrated services on the Platform:</b> We may share information about you with third-party vendors or service providers (including consultants, payment processors, and other service providers and integrated services) who need the information to provide their support services to us or you, or to provide their services to you on our behalf either directly or through the Platform. These services may include providing customer support, performing business and sales analysis, supporting our website functionality, facilitating payment processing, and supporting contests, surveys, and other features offered on our Platform. Such third-party vendors are not allowed to use the information for any purpose other than what it was provided for, and they are required to process and use the information in accordance with this Privacy Policy.</p>
        <p class="modal-para"><b>Third-party platforms to facilitate the additional offerings:</b> We may share information about you with third-party platforms that are used to create interactive forums between Service Providers and Customers to enable the Customers a more conducive environment to extend their take our service. The information shared with these platforms are limited to the information required to facilitate your participation in the forums and is based on your consent. However, the privacy practices of these platforms are independent of this Policy, and we suggest that you read through the privacy policies and terms and condition of the platforms relevant to you prior to consenting to being a part of any forums made available on these third-party platforms.</p>
        <p class="modal-para"><b>Legal Disclosures:</b> We may disclose information about you in response to a court order, or other governmental request. Without limitation to the foregoing, we reserve the right to disclose such information where we believe in good faith that such disclosure is necessary to:</p>
        <p class="modal-para ml-2">comply with applicable laws, regulations, court orders, government and law enforcement agencies’ requests;</p>
        <p class="modal-para ml-2">protect and defend Utsavlife’s or a third party's rights and property, or the safety of Utsavlife, our users, our employees, or others; or</p>
        <p class="modal-para ml-2">prevent, detect, investigate and take measures against criminal activity, fraud and misuse or unauthorized use of our Platform and/or to enforce our Terms and Conditions or other agreements or policies.</p>
        <p class="modal-para">To the extent permitted by law, we will attempt to give you prior notice before disclosing your information in response to such a request.</p>
        <p class="modal-para"><b>Business transfers:</b> In the event Utsavlife undergoes any merger, acquisition, or sale of company assets, in part or in full, with another company, or in the unlikely event that Utsavlife goes out of business or enters bankruptcy, user information would likely be one of the assets that is transferred or acquired by a third party. If any of these events were to happen, this Privacy Policy would continue to apply to your information and the party receiving your information may continue to use your information, but only consistent with this Privacy Policy.</p>
        <p class="modal-para"><b>Advertising and Analytics Partners:</b> We may share usage data with third-party advertisers, advertisement networks, and analytics providers through cookies and other similar technologies.</p>
        <p class="modal-para"><b>With Your Consent:</b> We may share and disclose information with your consent or at your direction.</p>
        <p class="modal-para"><b>Your information may be shared for reasons not described in this Policy; however, we will seek your consent before we do the same or share information upon your direction.</b></p>
        <h4 class="modal-heading" id="cross_border_data">J. Cross-Border Data Transfer</h4>
        <p class="modal-para">Your information including any Personal Information is stored, processed, and transferred in and to the Amazon Web Service (AWS) servers and databases located in Singapore, India and the USA. Utsavlife may also store, process, and transfer information in and to servers in other countries depending on the location of its affiliates and service providers.</p>
        <p class="modal-para">Please note that these countries may have differing (and potentially less stringent) privacy laws and that Personal Information can become subject to the laws and disclosure requirements of such countries, including disclosure to governmental bodies, regulatory agencies, and private persons, as a result of applicable governmental or regulatory inquiry, court order or other similar process.</p>
        <p class="modal-para">If you use our Platform from outside India, including in the USA, EU, EEA, and UK, your information may be transferred to, stored, and processed in India. By accessing our Platform or otherwise giving us information, you consent to the transfer of information to India and other countries outside your country of residence. If you are located in the EU and applicable law specifies relevant legal grounds for processing personal data, the legal grounds for our processing activities are to perform our contract(s) with you; to meet our legal obligations; and for our legitimate business purposes, including to improve our operation and Services and to detect and prevent fraud.</p>
        <p class="modal-para">We rely on legal bases to transfer information outside the EU, EEA and UK, and any Personal Information that we transfer will be protected in accordance with this Policy as well as with adequate protections in place in compliance with applicable Data Protection Laws and regulations.</p>
        <h4 class="modal-heading" id="duration_info">K. Duration for which your Information is Stored</h4>
        <p class="modal-para">Mostly, when you delete any of the information provided by you or when you delete your account, on the Platform, the same will be deleted from our servers too. However, in certain cases, we will retain your information for as long as it is required for us to retain for the purposes stated hereinabove, including for the purpose of complying with legal obligation or business compliances.</p>
        <p class="modal-para">Further, please note that we may not be able to delete all communications or photos, files, or other documents publicly made available by you on the Platform (for example: comments, feedback, etc.), however, we shall anonymize your Personal Information in such a way that you can no longer be identified as an individual in association with such information made available by you on the Platform. We will never disclose aggregated or de-identified information in a manner that could identify you as an individual.</p>
        <p class="modal-para">Note: If you wish to exercise any of your rights (as specified in <a href="#your_rights">‘Your Rights’</a> section below) to access, modify and delete any or all information stored about you, then you may do so by using the options provided within the Platform. You can always write to us at <a href="mailto:info@utsavlife.com">info@utsavlife.com</a> for any clarifications needed.</p>
        <h4 class="modal-heading" id="your_choice">L. Your Choices</h4>
        <p class="modal-para">Limit the information You provide: You always have an option to choose the information you provide to us, including the option to update or delete your information. However, please note that lack of certain information may not allow you the access to the Platform or any of its features, in part or in full.</p>
        <p class="modal-para">Limit the communications You receive from us: Further, you will also have the option to choose what kind of communication you would like to receive from us and whether you would like to receive such communication at all or not. However, there may be certain communications that are required for legal or security purposes, including changes to various legal agreements, that you may not be able to limit.</p>
        <p class="modal-para">Reject Cookies and other similar technologies: You may reject or remove cookies from your web browser; you will always have the option to change the default settings on your web browser if the same is set to ‘accept cookies’. However, please note that some Services offered on the Platform may not function or be available to you, when the cookies are rejected, removed, or disabled.</p>
        <h4 class="modal-heading" id="your_rights">M. Your Rights</h4>
        <p class="modal-para">In general, all Users have the rights specified herein this section. However, depending on where you are situated, you may have certain specific rights in respect of your Personal Information accorded by the laws of the country you are situated in. To understand <a href="#your_rights">Your rights</a></p>
        <p class="modal-para">If you are a User, you may exercise any of these rights by using the options provided to you within the Platform upon your login. If, however, you are facing any issues or require any clarifications, you can always write to us at the address noted in the <a href="#grievances">‘Grievances’</a> section below, and we will address your concerns to the extent required by the applicable law.</p>
        <p class="modal-para"><b>Right to Confirmation and Access:</b>You have the right to get confirmation and access to your Personal Information that is with us along with other supporting information.</p>
        <p class="modal-para"><b>Right to Correction:</b> You have the right to ask us to rectify your Personal Information that is with us that you think is inaccurate. You also have the right to ask us to update your Personal Information that you think is incomplete or out-of-date.</p>
        <p class="modal-para"><b>Right to be Forgotten:</b> You have the right to restrict or prevent the continuing disclosure of your Personal Information under certain circumstances.</p>
        <p class="modal-para"><b>Right to Erasure:</b> If you wish to withdraw/remove your Personal Information from our Platform, you have the right to request erasure of your Personal Information from our Platform. However, please note that such erasure will remove all your Personal Information from our Platform (except as specifically stated in this Policy) and may result in deletion of your account on the Platform permanently, and the same will not be retrievable.</p>
        <p class="modal-para">Remember, you are entitled to exercise your rights as stated above only with respect to your information, including Personal Information, and not that of other Users. Further, when we receive any requests or queries over email or physically to the address specified in the <a href="#grievances"> ‘Grievances’ </a> section below, then, as per the applicable Data Protection Laws, we may need to ask you a few additional information to verify your identity in association with the Platform and the request received.</p>
        <h4 class="modal-heading" id="info_sec">N. Information Security</h4>
        <p class="modal-para">We work to protect the security of your information during transmission by using Transport Layer Security (TLS) or Secure Sockets Layer (SSL) software (depending on your browser/Supported Device), which encrypts information you input in addition to maintaining security of your information as required under applicable laws.</p>
        <p class="modal-para">We maintain electronic, and procedural safeguards in connection with the collection, storage, and disclosure of Personal Information (including Sensitive Personal Information). Our security procedures mean that we may occasionally request proof of identity before we disclose Personal Information to you that belongs to you.</p>
        <p class="modal-para">However, no form or method of data storage or transmission system is fully secure, and we cannot guarantee that security provided by such system(s) is absolute and that your information will not be accessed, disclosed, or destroyed in the event of a breach of any of our security measures.</p>
        <p class="modal-para">It is important for you to protect your account against unauthorized access to or use of your password and to your computer and if you have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorized manner, you must immediately change your password or inform us, so that we are able to help you stop or prevent such unauthorized access. Be sure to sign off when you finish using a shared computer.</p>
        <p class="modal-para">All KYC information collected in accordance with this Policy are fully encrypted and cannot be accessed by any person other than the designated authority in Utsavlife.</p>
        <p class="modal-para">We try to ensure that the third parties who provide services to us under appropriate contracts take appropriate security measures to protect Personal Information in line with our policies.</p>
        <h4 class="modal-heading" id="personal_comm">O. Promotional Communications</h4>
        <p class="modal-para">You will always have the option to opt out of receiving some or all of our promotional communications through the setting provided within the Platform upon your login, by using the unsubscribe link in any email communications sent to you or by emailing <a href="mailto:info@utsavlife.com">info@utsavlife.com</a></p>
        <p class="modal-para">If you opt out of promotional communications, we may still send you transactional communications, such as service announcements, administrative and legal notices, and information about your account, without offering you the opportunity to opt out of these communications. If you no longer wish to use our Platform or receive any communications from us (except for those that are legally required), then you may delete your account by using the option enabled within the Platform or by writing to us at <a href="mailto:info@utsavlife.com">info@utsavlife.com</a>.</p>
        <p class="modal-para">Advertisers or ad companies working on their behalf sometimes use technology to serve the ads that appear on our sites directly to Your browser. They automatically receive Your IP address when this happens. They may also use cookies to measure the effectiveness of their ads and to personalize ad content. We do not have access to or control over cookies or other features that advertisers and third-party sites may use, and the information practices of these advertisers and third-party websites are not covered by our Policy. Please contact them directly for more information about their privacy practices.</p>
        <p class="modal-para">Please note that opting out of promotional email communications only affects future communications from us. If we have already provided your information to a third party (as stated in this Policy) before you changed your preferences or updated your information, you may have to change your preferences directly with that third party.</p>
        <p class="modal-para">We do not sell your Personal Information to third parties, and we do not use your name or name of your company in marketing statements without your consent.</p>
        <h4 class="modal-heading" id="interest_based_ads">P. Interest-Based Ads</h4>
        <p class="modal-para">On unaffiliated sites, Utsavlife may display interest-based advertising using information you make available to us when you interact with our Platform and Services. Interest-based ads, also sometimes referred to as personalised or targeted ads, are displayed to you based on information from activities such as registering with our Platform, visiting sites that contain Utsavlife content or ads. In providing interest-based ads, we follow applicable laws, as well as the Code for Self-Regulation in Advertising by the Advertising Standards Council of India and the Self-Regulatory Principles for Online Behavioural Advertising developed by the Digital Advertising Alliance (a coalition of marketing, online advertising, and consumer advocacy organizations) and other rules and guidelines issued by the Federal Trade Commission in respect of digital advertising.</p>
        <p class="modal-para">We do not provide any Personal Information to advertisers or to third party sites that display our interest-based ads. However, advertisers and other third-parties (including the ad networks, ad-serving companies, and other service providers they may use) may assume that users who interact with or click on a personalized ad or content are part of the group that the ad or content is directed towards. Also, some third-parties may provide us information about you (such as the sites where you have been shown ads or demographic information) from offline and online sources that we may use to provide you with more relevant and useful advertising.</p>
        <p class="modal-para">Advertisers or ad companies working on their behalf sometimes use technology to serve the ads that appear on our sites directly to your browser. They automatically receive your IP address when this happens. They may also use cookies to measure the effectiveness of their ads and to personalise ad content. We do not have access to or control over cookies or other features that advertisers and third-party sites may use, and the information practices of these advertisers and third-party websites are not covered by our Policy. Please contact them directly for more information about their privacy practices.</p>
        <h4 class="modal-heading" id="mod-privacy-policy">Q. Modification to Privacy Policy</h4>
        <p class="modal-para">Our business changes constantly and our Policy may change from time to time. We may, at our discretion (unless required by applicable laws to mandatorily do so), email periodic reminders of our notices and conditions, unless you have instructed us not to, but we encourage you to check our Platform frequently to see the recent changes. Unless stated otherwise, our current Policy applies to all information that we have about you and your account. We stand behind the promises we make, however, and will not materially change our policies and practices making them less protective of customer information collected in the past without your consent.</p>
        <h4 class="modal-heading" id="grievances">R. Privacy Grievances</h4>
        <p class="modal-para">If you have any questions about this Policy, wish to exercise your rights, have concerns about privacy of your data or any privacy related grievances in respect of the Platform, then please register your complaint with a thorough description via email to <a href="mailto:info@utsavlife.com">info@utsavlife.com</a> addressed to our grievance officer Mr. Vikrant Singh (Associate General Counsel) or via a registered post to the below address-</p>
        <p class="modal-para">Utsavlife Pvt. Ltd.</p>
        <p class="modal-para">R-16, Uttam Nagar west metro station, Gate Number 1 </p>
        <p class="modal-para">Metro pillar Number 690</p>
        <p class="modal-para">Bikaner wali Gali</p>
        <p class="modal-para">New Delhi 110059</p>
        <p class="modal-para">Privacy Policy – Version 1.0</p>
        <p class="modal-para">Last Updated on 16th JANUARY 2023</p>
      </div>
    </div>
  </div>
</div>