<style>
  .modal-body {
    max-height: 550px;
    overflow-y: auto;
    text-align: justify;
}
</style>
<!-- refferal Modal -->
<div class="modal fade" id="refferal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="new-heading mb-0">Referral</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h4 class="modal-heading">Terms & Conditions – Utsavlife Referral</h4>
        <p class="modal-para">Utsavlife User Referral Program (“Referral Program '') is made available through the Platform to all Users (as defined in our <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and Conditions</a>) who take once any service on the Platform.</p>
        <p class="modal-para">When we refer to “you”/ “your/s”, we collectively mean you as the User on the Platform. Similarly, when we speak of “Utsavlife”, “we”, “us”, and “our”, we collectively mean Sorting Hat Technologies Private Limited – a company incorporated in India and all its affiliates which have a license to host the Platform and offer Services. Kindly refer to the <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">About Utsavlife and the Platform</a> section of the Terms and Conditions to know which Utsavlife entity your Agreement (as defined in <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and Conditions</a>) will be with.</p>
        <p class="modal-para">Participation in our Referral Program is subject to the following terms and conditions (“Referral Terms''). Please take the time to read our Referral Terms and Platform Terms (as defined below). By participating in our Referral Program, you acknowledge that you have read, understood, and agree to be legally bound by the terms and conditions of these Referral Terms along with the Utsavlife’s <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and Conditions</a>, <a href="#" data-bs-toggle="modal" data-bs-target="#privacy" data-bs-dismiss="modal">Privacy Policy</a> and any other terms and conditions updated on the Platform or communicated to you from time to time (collectively referred to as the “Platform Terms''). If you do not agree to any of the terms and conditions, then please do not participate in our Referral Program or use our Service (as defined in our Terms and Conditions).</p>
        <p class="modal-para">Capitalized terms not defined in these Referral Terms shall have the meaning set forth in our Platform Terms.</p>
        <p class="modal-para">We may change these Referral Terms from time to time and will post any changes on the Platform or notify you via email, at our option, as soon as such changes are in effect.</p>
        <p class="modal-para"><b>Eligibility and Participation:</b> Participation in the Referral Program is voluntary, and all Users on the Platform are eligible to participate in the Referral Program. Accordingly, the <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">‘Age Requirements’</a> as stated in our Platform Terms shall continue to apply to all Users participating in the Referral Program.</p>
        <p class="modal-para">a. Once registered on the Platform as a User, you will have the option to generate a referral code within your account on the Platform or otherwise as directed on the Platform or as may be communicated to you by Utsavlife in writing (emails included) (“Referral Code”).</p>
        <p class="modal-para">b. You may refer friends or anyone by sending them the Referral Code via the Platform, email or through any other mode or platform.</p>
        <p class="modal-para">c. Once a person registers on the Platform as a User and purchases a Service (as defined in our <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and conditions</a>) using your Referral Code, such person shall be considered as your “Qualified Referral”.</p>
        <p class="modal-para">Please note that Referral Codes are unique to each User, and only when the person registering as a User applies your Referral Code will he/she/they be considered as your Qualified Referral. In other words, if the person you referred has failed to enter/apply the Referral Code that is unique to you while registering as a User or purchasing a Service (as applicable) on the Platform, then such person shall not be considered as your Qualified Referral, and you shall not be eligible to receive any Referral Rewards (defined below) in respect of that person. Similarly, any failure on your part to display or share the correct Referral Code shall not be the responsibility of Utsavlife.</p>
        <h4 class="modal-heading">A ‘Qualified Referral’ does NOT include the following:</h4>
        <p class="modal-para">a. Self-Referrals shall not be deemed as a Qualified Referral and Referral Rewards are not valid or payable for Self-Referrals. So, if your personal details, including but not limited to, last name, email address, IP address or website details, are the same as your Qualified Referral(s), then such referral will be deemed as a “Self-Referral''. Utsavlife, in its sole discretion, will determine the classification of any referral as a “Self-Referral''.</p>
        <p class="modal-para">b. Referrals made to any existing Users on the Platform shall not be deemed as Qualified Referrals; only a new user registering on the Platform using your Referral Code shall be considered as your Qualified Referral.</p>
        <p class="modal-para">c. If a User referred by you initiates cancellation or refund of the Service on the Platform within 30 (thirty) days (or such other number of days as mentioned on the Platform) from the date of purchase of the Service on the Platform, or if there have been any chargebacks by such User, then such User referred by you shall not be deemed as a Qualified Referral, and you shall not be entitled to any Referral Rewards in respect of such User.</p>
        <p class="modal-para">d. No referral by you shall be considered as a Qualified Referral, if Utsavlife suspects any fraudulent activity by you to increase your Qualified Referrals, including without limitation, the use of any software that generates real and fictitious information, multiple accounts from the same users referred by you, or any activity that does not comply with the Referral Terms and/or the Platform Terms. In these cases, Utsavlife shall also have the right to terminate your account and access to the Platform at its sole discretion.</p>
        <p class="modal-para">e. Where any User referred by you receives from or was offered coupons, refunds, credits or discounts by you to purchase a Service on the Platform and such offering was not authorised by Utsavlife, then such purchase by the User referred by you shall not amount to a Qualified Referral.</p>
        <p class="modal-para">f. If it is found by Utsavlife that you have adopted marketing practices in contravention to these Referral Terms or that we deem to be unethical or are likely to attract fraudulent signups, then such Users referred by you shall not be deemed as Qualified Referrals.</p>
        <p class="modal-para">g. Any referral that is deemed to be in contravention of these Referral Terms, Platform Terms and/or any other terms as communicated to you by Utsavlife in writing (emails included) at the sole discretion of Utsavlife, shall not be deemed as a Qualified Referral.</p>
        <p class="modal-para"><b> Referral Rewards:</b> For each Qualified Referral you may be entitled to receive a reward in the form of cash, gift vouchers or otherwise in kind as detailed out  or elsewhere on the Platform and/or as communicated to you in writing (emails included) from time to time (“Referral Rewards'') (as defined below). These Referral Rewards, and the duration for which these Referral Rewards are offered, are as detailed out on the Platform and/or as communicated to you in writing (emails included). The Referral Rewards shall be determined by Utsavlife at its sole discretion and the same may vary from time to time, unless otherwise specifically communicated to you in writing (emails included).</p>
        <p class="modal-para">It is hereby clarified that the Referral Rewards shall be inclusive of all applicable taxes and subject to deduction of applicable taxes. Utsavlife shall not be responsible to pay any taxes on the Referral Rewards in any manner.</p>
        <p class="modal-para"><b>Disbursement of Referral Rewards:</b> We will track the Qualified Referrals generated by you through your Referral Code, and we will make this information available to you either on your dashboard on the Platform or otherwise communicate to you (including via email). To permit accurate tracking, reporting, and commission accrual, you must ensure that the Referral Codes are properly made available to your referrals. Further, please note the below-</p>
        <p class="modal-para">a. Based on your Qualified Referrals, you shall be entitled to such Referral Rewards as determined by Utsavlife at the time of its accrual. The information regarding the Referral Rewards you may be entitled to shall be made available to you either on your dashboard or shall be communicated to you by Utsavlife including via email.</p>
        <p class="modal-para">b. The Referral Rewards shall be disbursed to you upon you claiming the same either through your dashboard or through such other mechanisms as may be communicated to you by Utsavlife. Unless duly claimed by you in accordance with the mechanism communicated by Utsavlife, Utsavlife shall not be obligated to disburse any Referral Reward to you on any account whatsoever.</p>
        <p class="modal-para">c. You are entitled to Referral Rewards only for your Qualified Referrals as verified by Utsavlife in accordance with these Referral Terms and other terms as may be communicated to you in writing (emails included).</p>
        <p class="modal-para">d. Referral Rewards shall be disbursed to you based on the current information provided by you on the Platform, including your email address and phone number. In case of any changes, it shall be your sole responsibility to update the information in your dashboard or by writing to <a href="mailto:info@utsavlife.com">info@utsavlife.com</a>, and Utsavlife shall not be liable for the same.</p>
        <p class="modal-para">e. If there are any cash-based Referral Rewards, then the payment of the same may be facilitated to you subject to your submission of the required ‘Know your Customer’ (KYC) documents, and any other tax related documents as may be required by Utsavlife.</p>
        <p class="modal-para">f. It is hereby clarified that the Referral Rewards shall be inclusive of all applicable taxes and subject to deduction of applicable taxes. Utsavlife shall not be responsible to pay any taxes on the Referral Rewards in any manner.</p>
        <p class="modal-para">g. Utsavlife reserves the right to immediately cancel or withhold for later review any Referral Rewards that fail to meet the criteria of a ‘Qualified Referral’. You are responsible for monitoring the disbursement, denial, and withholding of Referral Rewards; Utsavlife is not obligated to actively notify you of the status of the Referral Rewards except as stated hereunder. If you have any questions about your Referral Rewards that have been cancelled or withheld, you have thirty (30) days from the day such Referral Reward would have accrued to contact Utsavlife requesting the information for such cancellation or withholding. Any changes to decisions about cancelled or withheld Referral Reward are strictly made in Utsavlife’s sole discretion</p>
        <p class="modal-para">h. Utsavlife reserves the right to immediately cancel or withhold for later review any Referral Rewards that fail to meet the criteria of a ‘Qualified Referral’. You are responsible for monitoring the disbursement, denial, and withholding of Referral Rewards; Utsavlife is not obligated to actively notify you of the status of the Referral Rewards except as stated hereunder. If you have any questions about your Referral Rewards that have been cancelled or withheld, you have thirty (30) days from the day such Referral Reward would have accrued to contact Utsavlife requesting the information for such cancellation or withholding. Any changes to decisions about cancelled or withheld Referral Reward are strictly made in Utsavlife’s sole discretion
        </p>
        <p class="modal-para"><b>Marketing and Promotions:</b></p>
        <p class="modal-para">a. You shall bear your own costs and expenses related to marketing and promoting Utsavlife. Utsavlife is not obligated to reimburse or credit you for any marketing expenses, unless it has been specifically agreed by Utsavlife in writing (emails included).</p>
        <p class="modal-para">b. You hereby represent and warrant that your marketing practices do not violate any of the following restrictions. you shall -</p>
        <p class="modal-para">not advertise Utsavlife as a free product.</p>
        <p class="modal-para">not make any false, misleading, or disparaging statements with respect to the Utsavlife, its employees, its customers, its affiliates, its Services, or the Referral Program.</p>
        <p class="modal-para">not use traffic that is generated by, including, but not limited to, pay to click, pay to read, banner exchanges, click exchanges, cost-per-view advertising, pop-up/under, spam, purchased traffic, or similar methods without prior written consent from Utsavlife.</p>
        <p class="modal-para">not create websites or advertisements that copy, imitate, or resemble the look and feel of Utsavlife’s Services.</p>
        <p class="modal-para">not engage in the advertisement of business-opportunity websites or use marketing practices that attract fraudulent or short-term customers.</p>
        <p class="modal-para">not engage in any marketing activity that may harm the reputation or credibility of Utsavlife, including but not limited to using low-quality marketing materials, or advertising on any website that promotes violence, discrimination based on race, sex, religion, nationality, disability, sexual orientation or age, or any illegal activities, or violates the intellectual property or other rights of a third party.</p>
        <p class="modal-para">include a physical mailing address and unsubscribe information for any marketing email sent promoting Utsavlife’s Services.</p>
        <p class="modal-para">communicate clearly that they, not Utsavlife, are the sender of all marketing communications related to the promotion of Utsavlife’s Services as part of the Referral Program.</p>
        <p class="modal-para">not engage in any marketing or promotional activities that violate applicable laws, rules, or regulations.</p>
        <p class="modal-para">not market using facsimile, broadcast, telemarketing, text message marketing, or other offline marketing methods regarding Utsavlife and/or its Services without the express written consent of Utsavlife.</p>
        <p class="modal-para">not use malware or spyware to market or promote Utsavlife’s Services.</p>
        <p class="modal-para"><b>Coupons and Promotional Codes:</b> You may only use coupons and promotional codes that are provided exclusively through the Referral Program. We do not provide any rewards or incentives to Qualified Referrals, unless otherwise specifically communicated in writing (digital medium included), and Utsavlife reserves the right to cancel any and all Referral Rewards where it finds evidence of any activity run by you that claims or otherwise communicates offering of rewards or incentives to Qualified Referrals by Utsavlife. Further, we do not encourage you to offer such incentives or rewards to promote the use of your Referral Code in any manner.</p>
        <p class="modal-para"><b>Prohibited Activities:</b></p>
        <p class="modal-para">a. Except as permitted herein, you shall not and are not authorized to –</p>
        <p class="modal-para ml-2">use Utsavlife’s trademark or other intellectual property, including without limitation, the Referral Codes (collectively, “Utsavlife’s Intellectual Property” or “Utsavlife’s IP”) without Utsavlife’s express prior written permission;</p>
        <p class="modal-para ml-2">use Utsavlife’s name (or any variation or misspelling thereof or other terms that are confusingly similar to any of the foregoing) in a domain name, any metatags, advertising, search terms, code, or otherwise; or</p>
        <p class="modal-para ml-2">act in any way that causes or could cause any confusion concerning the source of, or your association with Utsavlife’s Services. Your use of Utsavlife’s IP in any manner, other than as expressly permitted hereunder and/or as communicated to you by Utsavlife in writing (emails included) shall constitute infringement of Utsavlife’s IP rights and Utsavlife shall have the right to enforce its rights against you which may subject you to liabilities including without limitation to pay Utsavlife’s legal fees and costs.</p>
        <p class="modal-para">b. You are prohibited from bidding on any Utsavlife trademarks, or any variations and misspellings thereof. Examples of prohibited keywords are “Utsavlife”, “Utsavlifeapp”, “Utsavlife.com”, “Utsavlife.in”, “Utsavlifeapp.co”, “india.Utsavlife.com," “Utsavlife hosting”, “Utsavlife domains”.</p>
        <p class="modal-para">c. You are prohibited from bidding on keywords containing Utsavlife trademarks plus an additional term such as [Utsavlife coupons], [Utsavlife promotions], and [Utsavlife promos]. Further, you are NOT permitted to phrase match any of these keywords.</p>
        <p class="modal-para">d. You are prohibited from outranking Utsavlife's internal paid search ad on any keywords.</p>
        <p class="modal-para">e. You are prohibited from direct linking to the Platform from any paid search ads.</p>
        <p class="modal-para">f. You are prohibited from using <a href="https://www.utsavlife.com/">www.utsavlife.com</a> as a display URL.</p>
        <p class="modal-para">If you are determined to be in violation of this section, then your participation in the Referral Program may be terminated. For more information on match types, please visit Google's overview of <a href="https://support.google.com/google-ads/answer/7478529?hl=en&visit_id=637175332283452149-3617255890&rd=1">match types</a>.</p>
        <p class="modal-para">IP Licenses and Use:</p>
        <p class="modal-para">Subject to the limitations set forth in these Referral Terms, we grant you a non-exclusive, non-transferable, non-assignable, revocable license to (i) provide access to Utsavlife’s website through the Referral Codes solely in accordance with these Referral Terms; and (ii) use Utsavlife’s IP for the sole purpose of promoting Utsavlife’s Services in accordance with these Referral Terms and/or any terms as may be communicated to you in writing (emails included).</p>
        <p class="modal-para">You shall not alter, modify, or change Utsavlife’s IP in any way or use Utsavlife’s IP in any manner that is disparaging or that otherwise portrays Utsavlife, any Utsavlife employee, representative or customer in a negative light. You are only entitled to use Utsavlife’s IP in compliance with these Referral Terms, Platform Terms and/or any terms as may be communicated to you in writing (emails included).</p>
        <p class="modal-para">Your license to use Utsavlife’s IP shall immediately terminate upon the termination of your participation in the Referral Program for any reason. We reserve all of our rights in Utsavlife’s IP and your license to use Utsavlife’s IP is limited to the manner described herein.</p>
        <p class="modal-para"><b>General Terms:</b></p>
        <p class="modal-para">a. Utsavlife reserves the right to modify or cancel the Referral Program in its entirety without prior notice. Similarly, Utsavlife reserves the right to modify, add or delete any of the terms under this Referral Terms at any point of time at its sole discretion without serving any prior intimation. Intimation of any change, modification, addition, deletion in the Referral Terms will be updated on this page or in the relevant section of the Platform.</p>
        <p class="modal-para">b. Referral Rewards are non-transferable; non-endurable; non- exchangeable for equivalent amounts of money or anything of value. Utsavlife does not promise/promote to do the same.</p>
        <p class="modal-para">Referral Rewards are time-bound, and accordingly the same must be availed within the duration specified on the Platform and/or as communicated to you in writing (emails included).</p>
        <p class="modal-para">Utsavlife reserves the right to cancel, revoke, or otherwise prevent the issuance of Referral Rewards in any suspected case of fraudulent use or misuse of this Referral Program. Spam and/or illegal emails are not permitted.</p>
        <p class="modal-para">Referral <a href="#" data-bs-toggle="modal" data-bs-target="#terms" data-bs-dismiss="modal">Terms and Conditions</a> – Version 1.0</p>
        <p class="modal-para">Last Updated on 16th JANUARY, 2023</p>
      </div>
    </div>
  </div>
</div>