<style>
  .modal-body {
    max-height: 550px;
    overflow-y: auto;
    text-align: justify;
}
</style>
<!-- terms Modal -->
<div class="modal fade" id="terms" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="new-heading mb-0">Terms & Condition</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h4 class="modal-heading">Utsavlife Platform - Terms and Conditions</h4>
        <h4 class="modal-heading2">Table of Services:</h4>
      <ul class="ml-2">
        <li><a href="#about">A. About Utsavlife and the Platform</a></li>
        <li><a href="#platform">B. Platform Services</a></li>
        <li><a href="#rights_to_accounts">C. Right to Access and Account Creation</a></li>
        <li><a href="#booking_terms">D. Booking Terms</a></li>
        <li><a href="#pricing">E. Pricing, Payments and Refund</a></li>
        <li><a href="#use_of_platform2">F. Use of the Platform</a></li>
        <li><a href="#content_conduct">G. Service and Conduct</a></li>
        <li><a href="#communications">H. Communications</a></li>
        <li><a href="#processing_personal_information">I. Processing of Personal Information</a></li>
        <li><a href="#intellectual_property_license">J. Intellectual Property and License to User-generated Service</a></li>
        <li><a href="#feedback">K. Pricedback</a></li>
        <li><a href="#copyrights">L. Copyrights, Trademarks and other Intellectual Property Rights</a></li>
        <li><a href="#claims_against_user_content">M. Claims Against User-generated Service</a></li>
        <li><a href="#unacademy_rights">N. Utsavlife’s Rights</a></li>
        <li><a href="#platform_availability">O. Platform Availability</a></li>
        <li><a href="#deletion_of_account">P. Deletion of Account</a></li>
        <li><a href="#disclaimer">Q. Disclaimer</a></li>
        <li><a href="#limitation_of_liability">R. Limitation of Liability</a></li>
        <li><a href="#indemnity_and_release">S. Indemnity and Release</a></li>
        <li><a href="#governing_laws">T. Applicable Laws and Jurisdiction</a></li>
        <li><a href="#general_provisions">U. General Provisions</a></li>
        <li><a href="#user_support">V. Contact for User Support/Queries</a></li>
        <li><a href="#contact_us">W. Contact Us</a></li>
      </ul>    
      <p class="modal-para mt-2">Welcome to Utsavlife! We hope that you have a great experience using our Platform.</p>
      <p class="modal-para">These Terms and Conditions (“Terms and Conditions”) set out the terms and conditions for use of <a href="http://utsavlife.com/">http://www.utsavlife.com/</a> (the “Site”), the mobile application(s) (the “Application”) and any features, subdomains, Service (except as specified hereunder), functionality, products, services (including the Services), media, applications, or solutions offered on or through the Site and/or the Application and/or through any modes, medium, platform or format, including through Secure Digital (‘SD’) cards, tablets or other storage/transmitting device (hereinafter collectively referred to as the “Platform”/ “Utsavlife Platform”).</p>
      <p class="modal-para">These Terms and Conditions apply to all users of the Platform, including without limitation, all persons who create and / or make available Services (as defined under the ‘Intellectual Property’ section below) on the Platform (referred to as “Service providers'') and users who access the Platform to Buy service or sell service (referred to as “Customers'') or users who access the Platform otherwise (collectively referred to as “you”, “your”, or “User(s)”). These Terms and Conditions along with the Privacy Policy, Refund Policy, Cookies Policy, Accessibility Statement, the User Guidelines and any other terms and conditions, rules, policies or guidelines included in these Terms and Conditions or Privacy Policy by reference and/or as updated on the Platform or otherwise communicated to you from time to time (including terms and conditions of other third party platforms that may be used or accessed for gaining access to the Platform or using the Services on the Platform (collectively referred to as the “Platform Term(s)”), defines the relationship between you and Utsavlife, and they shall govern your use of the Platform and the Services (defined below) offered therein. Your access to the Platform is subject to your acceptance of the Platform Terms and such acceptance of the Platform Terms forms a legally binding agreement between you and Utsavlife (“Agreement”). Hence, please take your time to read the Platform Terms in their entirety.</p>
      <p class="modal-para">From time-to-time, updated versions of the Platform Terms may be made available as aforesaid for your reference. By visiting and accessing the Platform, providing your Personal Information (as defined in the Privacy Policy), using the Services offered or by otherwise signalling your agreement when the option is presented to you, you hereby expressly accept and agree to the Platform Terms. If you do not agree to any of the terms or do not wish to be bound by them, then please do not use the Platform in any manner.</p>
      <p class="modal-para">When we speak of “Utsavlife”, “we”, “us”, and “our”, we collectively mean Royal Utsavlife Private Limited – a company incorporated in India and all of its affiliates which have license to host the Platform and offer Services. Kindly refer to the ‘About Utsavlife and the Platform’ section of these Terms and Conditions to know which Utsavlife entity your Agreement will be with.</p>
      <p class="modal-para">All capitalized terms are defined/have the meaning assigned to it under these Terms and Conditions. In other words, if you find any word herein that has its first letter capitalized, then it means that we have explained the meaning such word has in the context of these Terms and Conditions and/or the Platform Terms; if not here, then it will be provided in the relevant Platform Terms – when we refer to any such term in these Terms and Conditions, we will try and specify where in the Platform Terms you can find the meaning/definition.</p>
      <h4 class="modal-heading" id="about">A. About Utsavlife and the Platform</h4>
      <p class="modal-para">In India, the Platform is owned, managed, operated and offered by Royal Utsavlife Private Limited, a company incorporated under the (Indian) Companies Act, 2013, having its registered office at R -16 Uttam Nagar west metro station Gate Number -1, Metro pillar Number -690 Bikaner wali Gali Delhi 110059, India (“Utsavlife India”). In any jurisdiction other than India, wherever Services are rendered through the Platform, the same is offered by Utsavlife India and / or its affiliates (as relevant pursuant to appropriate intra group contractual arrangements). For knowing with which entity of Utsavlife your Agreement will be, please refer the list in Annexure A below.</p>
      <h4 class="modal-heading" id="platform">B. Platform Services:</h4>
      <p class="modal-para">Utsavlife Platform is an online service platform enabling Service providers to create and offer Services in various Event including Tent, Decorators, Event planner, Marriage Hall, Catrine, Photographer, Videographer, Musical Group, DJ, Stage Show, Dance Show, Bollywood Dance, Singing Show, Designer, Decorator, etc in a diverse range of categories through various modes and means (“Service Provider Service'') and publish and make available such Service Provider Service to the Customers. Utsavlife acts as an intermediary between the Service providers and Customers [in accordance with the Information Technology Act, 2000, or the Digital Millennium Copyright Act (as amended from time to time)] or other equivalent / similar legislations and makes available the Service Provider Service to the Customers, including through Booking offerings (refer to the Booking Terms below to know more). </p>
      <p class="modal-para">Further, Utsavlife may offer certain products/services to you in collaboration with one or more of the Utsavlife Group Platforms (as defined under the Privacy Policy). In such cases, to the extent that such product/services are made available to you through the Platform, the Platform Terms shall continue to apply to you.</p>
      <p class="modal-para">For the purpose of the Platform Terms, usage of the terms “Platform Services”/ “Services” shall mean and include all the services referred to in this section and such other products or services as may be offered by Utsavlife.</p>
      <p class="modal-para">You agree and acknowledge that Utsavlife has no control over and assumes no responsibility for, the User-generated Service (as defined under the ‘Intellectual Property’ section below) and by using the Platform, you expressly relieve Utsavlife from any and all liability arising from the User-generated Service.</p>
      <p class="modal-para">You agree and acknowledge that Utsavlife shall have the right at any time to change or discontinue any Service, product, aspect, or feature of the Platform, including without limitation to, the User-generated Service (to the extent it is permitted to, or required, by virtue of being an ‘intermediary’), its availability and Supported/Compatible device required to access or use the Services. Utsavlife reserves the right to terminate your Booking and / or restrict your access to the Platform, if you choose not to provide / partially provide the requested information.</p>
      <h4 class="modal-heading" id="rights_to_accounts">C. Right to Access and Account Creation</h4>
      <p class="modal-para">As a customer, to access the Platform and use certain Services, you will be required to register and create an account on the Platform by providing the requested details.</p>
      <p class="modal-para">To register on the Utsavlife Platform you must meet the ‘Age Requirements’ specified hereinbelow. By using the Utsavlife Platform, you, through your actions, affirm that the Age Requirements are met.</p>
      <p class="modal-para">You can register on the Platform for free however, certain Services offered on the Platform may be chargeable. Please review the Service offerings on our Site or Application(s). You are not obligated to Booking any product or use any Service offered on the Platform.</p>
      <p class="modal-para"><b> Age Requirements to register and use on the Platform (“Age Requirements”):</b></p>
      <ul class="ml-2">
        <li>If you are a resident of India or any other country (except USA, UK or EU countries), then you must have attained at least 18 (eighteen) years of age to register and use the Utsavlife Platform;</li>
        <li>If you are a resident of the European Union (EU) country and have attained at least 16 (sixteen) years of age, then you are permitted to register and use the Utsavlife Platform; and</li>
        <li>If you are a resident of the United States of America (USA) or United Kingdom (UK) and have attained at least 13 (thirteen) years of age, then you can register and use the Utsavlife Platform.</li>
        <li>If you are a resident of the US, UK or EU countries and are between the ages 13 and 18/ 16 and 18 respectively or if you are resident of any other country and are considered to be of any age determined for use of internet services but are less than the contractual age determined by the applicable laws of such country, then by using the Platform, you confirm to us that your use of the Platform is with the permission of your Parent(s) (as defined below), and your Parent has read, agreed and accepted to the Agreement; and in the event of any dispute between you and Utsavlife pursuant to your Agreement with us, the terms of our Agreement shall be applicable to and enforceable against your Parent.</li>
      </ul>
      <p class="modal-para">A Customer who does not fulfil the Age Requirements mentioned above (as may be revised as per applicable laws from time to time) and is desirous of registering on the Platform i.e., if a customer is a “Minor”/ “Child”, then the Customer may use the Platform with the consent of, and under the supervision of, their parent or legal guardian (“Parent”). Accordingly, in such a case, the Parent must agree to the Platform Terms at the time of their registration on the Platform. Please note that minors/children are not by themselves eligible to register on the Platform. When a Minor/Child uses the Platform, we assume that the Parent of such Minor/Child has enabled the Minor/Child’s usage of the Platform by agreeing to the Platform Terms and that such usage is under the supervision of their Parent.</p>
      <p class="modal-para">Utsavlife reserves the right to terminate your Booking and / or restrict your access to the Platform, if it is discovered that you do not meet the Age Requirements and/or the consent to register and use the Platform is not obtained as above. You acknowledge that Utsavlife does not have the responsibility to ensure that You conform to the aforesaid Age Requirements. It shall be Your sole responsibility to ensure that the required qualifications are met.</p>
      <p class="modal-para">If you are a Service Provider, your access and use of the Platform may additionally be subject to separate agreement(s) with Utsavlife and shall be collectively governed by the terms of such agreement, the Terms and Conditions, other Platform Terms, and such other terms as may be communicated or agreed with the Service Provider from time to time.</p>
      <p class="modal-para">Further, the permission given by Utsavlife to access and use the Platform under these Terms and Conditions is subject to the following conditions:</p>
      <p class="modal-para">1. You agree not to distribute in any medium any part of the Platform, Service Provider Service or the Utsavlife Service (as defined below) without Utsavlife’s prior written authorization.</p>
      <p class="modal-para">2. You agree not to alter or modify any part of the Platform.</p>
      <p class="modal-para">3. You agree not to access User-generated Service of any other User through any technology or means other than the User-generated Service you have legitimate access to.</p>
      <p class="modal-para">4. You agree not to use the Platform for any of the following commercial uses unless you obtain Utsavlife’s prior written approval:</p>
      <p class="modal-para ml-2">the sale of access to the Platform;</p>
      <p class="modal-para ml-2">the sale of advertising, sponsorships, or promotions placed on or within the Platform or Service Provider Service; or</p>
      <p class="modal-para ml-2">the sale of advertising, sponsorships, or promotions of any third-party page or website.</p>
      <p class="modal-para">5. You agree to receive installs and updates from time to time from Utsavlife. These updates are designed to improve, enhance, and further develop the Platform and may take the form of bug fixes, enhanced functions, new software modules and completely new versions. You agree to receive such updates (and permit Utsavlife to deliver these to you) as part of your use of the Platform.</p>
      <p class="modal-para">6. You agree not to use or launch any automated system, including without limitation, “robots,” “spiders,” or “offline readers,” that accesses the Platform in a manner that sends more request messages to Utsavlife’s servers in a given period of time than a human can reasonably produce in the same period by using a conventional on-line web browser. Notwithstanding the foregoing, Utsavlife grants the operators of public search engines permission to use spiders to copy materials from the Site for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such materials. Utsavlife reserves the right to revoke these exceptions either generally or in specific cases at any time with or without providing any notice in this regard. You agree not to collect or harvest any personally identifiable information, including account names, from the Platform, nor to use the communication systems provided by the Platform, unless otherwise mentioned herein.</p>
      <p class="modal-para">7. You may post reviews, comments and other Service; send other communications; and submit suggestions, ideas, comments, questions or other information as long as the Service is not illegal, obscene, threatening, defamatory, invasive of privacy, infringement of intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any other form of spam. In other words, ensure that your conduct on the Platform is in accordance with the Platform Terms, including the User Guidelines.</p>
      <p class="modal-para">8. In your use of the Platform, you will, at all times, comply with all applicable laws and regulations.</p>
      <p class="modal-para">9. Utsavlife reserves the right to discontinue any aspect of the Platform at any time with or without notice at its sole discretion.</p>
      <p class="modal-para">You are responsible for maintaining the confidentiality of your account and password to access the Platform. You acknowledge that your account is personal to you and agree not to provide any other person with access to the Platform and to restrict access to your device to prevent any unauthorized access to your account. You agree to accept responsibility for all activities that occur under your account. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your username, password, or other Personal Information. You should take all necessary steps to ensure that the password is kept confidential and secure at all times, and if you have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorized manner, you agree to immediately change your password or inform us of any unauthorized access to or use of your username or password, so that we are able to help you stop or prevent such unauthorized access. Please ensure that the details you provide us are correct and complete.</p>
      <p class="modal-para">You represent that the information provided by you at the time of the registration is correct, true and accurate, and you agree to update the same as and when there is any change in the said information. Please read our Privacy Policy to understand how we handle your information.</p>
      <p class="modal-para">Please note that we reserve the right to reject or put on-hold your registration on the Platform as may be required to comply with any legal and regulatory provisions, and also reserve the right to refuse access to the Platform, terminate accounts, remove Service at any time without providing any notice to you, and/or reserve the right to disable any account, feature, or identifiers, whether chosen by you or provided by us, at any time if, in our opinion, the said identifiers or you have violated any provision of the Platform Terms.</p>
      <p class="modal-para">Further, to access the Platform, create, publish and/or view the User-generated Service on the Platform, you will need to use a “Supported/Compatible Device” which means a personal computer, mobile phone, portable media player, or other electronic device that meets the system and compatibility requirements and on which you are authorized to operate the Platform. The Supported/Compatible Devices to access the Platform and/or avail the Services may change from time to time and, in some cases, whether a device is (or remains) a Supported/Compatible Device may depend on software or systems provided or maintained by the device manufacturer or other third parties. Accordingly, devices that are Supported/Compatible Devices at one time may cease to be Supported/Compatible Devices in the future. Thus, kindly make sure that the device that you use is compatible with our system/software to use the Platform and avail the Services offered therein.</p>
      <h4 class="modal-heading" id="booking_terms">D. Booking terms</h4>
      <p class="modal-para">For Customers, Utsavlife does not charge any price for Booked Service creation. However, certain Services offered by Utsavlife may be chargeable. Accordingly, access to certain Services and features is offered by Utsavlife through a multi- tiered paid Booking plan(s) or purchases; the details of the Services and applicable features along with their corresponding prices can be found on our Site and/or Application (“Booking”/ “Booking Service''). You can Book service by following the instructions you encounter as you navigate through the Platform.</p>
      <p class="modal-para">The terms that are applicable to Your Booking of Service(s) -</p>
      <p class="modal-para">Booking of a Service will allow you access only to the Service available under the category of Service for which you have Booked the Service.</p>
      <p class="modal-para">The Services offered, and the validity/term of your Service (“Booking Period”) may vary depending on the plan you may Booking. Hence, before you proceed to Book any Service, please read and understand the details of the Service(s) you intend to Booking on the Platform. If you are unclear about any part of the Service offering or need further clarification, then please feel free to write to us prior to your Booking at the email address provided in the ‘Contact for User Support/Queries’ section below.</p>
      <p class="modal-para">We may personalize Services and feature them as part of Bookings, including showing you recommendations on Service in the subscribed category, and other related categories that might be of interest to you. We also endeavour to continuously improve the Booking offerings to improve your Platform experience.</p>
      <p class="modal-para">The Service is of a personal nature and is solely for the benefit of the person and is not allowed to be resold by you or transferred to or shared with any other person for consideration or otherwise. In the event we get to know that any User has resold / transferred / shared Booking with another person, then Utsavlife retains the right to cancel/terminate the Booking forthwith.</p>
      <p class="modal-para">Due to the limitations, if any, imposed on us by our Service providers (who own the Service Provider), the Service Provider we make available to you under any Booking offering are subject to restrictions on viewing access and on the length of time we make them available to you. These restrictions may change over time as we add new features, devices and Service to our Booking Service. Illustratively, following are some of the restrictions that are applicable to your access to the Service (made available through Booking Service or otherwise):</p>
      <p class="modal-para">Depending on the Booking Service you have Booked, you may be given access to certain additional Services and features. The additional terms applicable to each of these additional Services may be made available to you on the Platform in the form of terms and conditions or FAQs (Frequently Asked Questions) for that specific Service or may be otherwise communicated to you. Hence, please be sure to go through the Platform Terms to understand the additional services, if any made available to you, and how you can avail the same.</p>
      <h4 class="modal-heading" id="pricing">E. Pricing, Payments and Refunds</h4>
      <p class="modal-para">1. Pricing and Payments: You can Book a Service of your choice for any category(ies) of Service by following instructions on the Platform and making the payment applicable for the Booking you intend to Book.</p>
      <p class="modal-para">Please read the below terms applicable for the Book of your Platform Booking. The below terms are to be read with any other terms communicated to you at the time of Booking of your Booking:</p>
      <p class="modal-para">a. You agree to pay all Booking prices and charges that are attributable to your account on the Platform and that you are solely responsible for payment of these prices and charges. The Bookings are payable in full and in advance and are valid until the completion of the applicable Booking Period or until otherwise cancelled or terminated in accordance with the terms of this Agreement.</p>
      <p class="modal-para">b. If you have specifically authorized us, then the payments for the applicable Bookings are automatically charged at the beginning of each billing period, unless you withdraw your authorization or submit a cancellation request to us directly through your account prior to the start of the billing period or in writing via email to the address specified in the ‘Contact for User Support/Queries’ section below. The payment for your Booking will be charged upon the anniversary of its billing period if the payments for Booking are in more than a single tranche. Subject to your specific authorization and applicable laws, you agree that Utsavlife may charge any recurring service to the credit card or debit card or account that you provide/link at the time of your first Booking of the Booking or as updated by you through your account on the Platform, provided such updating takes place prior to upcoming billing period.</p>
      <p class="modal-para">c. If you have not completed payments for your Bookings, we may restrict / suspend your booked service(s). until it becomes current and paid in full.</p>
      <p class="modal-para">d. We reserve the right to pursue the price owed to us using collection methods which may include charging other payment methods on file with us and/or retaining collection agencies or legal counsel.</p>
      <p class="modal-para">e. The entity within the Utsavlife group to which your payments will be made will be on the basis of Annexure 1.</p>
      <p class="modal-para">f. Your payments to Utsavlife shall be subject to applicable taxes including without limitation Goods and Service Taxes (GST) and Value Added Taxes (VAT) or other similar taxes as may be applicable in your country of residence/from where you have created your account on the Platform/ Booking the underlying Bookings.</p>
      <p class="modal-para">g. We reserve the right to change/revise the pricing of the Bookings. For existing Bookings for which the applicable prices have been already received by us, we will implement the price changes during the next billing period.</p>
      <p class="modal-para">h. We further reserve the right to offer custom plans and pricing (including discounts and / or special offers) in addition to what is offered on the Platform, which include offering custom billing and payment terms, that are different from our standard terms.</p>
      <p class="modal-para">i. We use third-party payment gateways and/or aggregators to process payments applicable to the Services offered by us. Third-party payment gateway(s) made available to you may vary depending on the Booking you choose. Similarly, we have also enabled integration of third-party payment providers to facilitate better payment options to you, which may vary depending on your territory or the Booking you choose. Third-party payment gateways/aggregators and third- party payment providers shall collectively be referred to as “Third-Party Service Providers”.</p>
      <p class="modal-para">Third-Party Service Providers may also charge you prices to use or access their services and may require your Personal Information to complete any transaction for the Platform. Further, to facilitate completion of your payments to us through the Platform or avail the payment options provided to you, you may be redirected to an external website operated by the Third-Party Service Provider. We cannot and do not (i) guarantee the adequacy of the privacy and security practices employed by or the Service and media provided by the Third-Party Service Provider or its respective websites or (ii) control collection or use of your Personal Information by such Third-Party Service Provider. Hence, prior to using any services offered by a Third-Party Service Provider, we suggest that you read their terms and conditions, privacy policy and other policies that may apply, to understand their terms of usage and to understand how your Personal information is being processed. Utsavlife is not affiliated to any Third-Party Service Provider and neither Utsavlife nor any of the Third-Party Service Providers are agents or employees of the other.</p>
      <p class="modal-para">Further, pursuant to the payment option you may choose, you may be required to enter into a separate agreement with the relevant Third-Party Service Provider. This agreement with the Third-Party Service Provider is an independent contract/agreement between you and such Third-Party Service Provider and Utsavlife shall in no manner be a party to the same. Utsavlife is only facilitating various payment options to you and is not offering the payment by itself in any manner.</p>
      <p class="modal-para">j. You agree that you are solely responsible for all charges that occur through such Third-Party Service Providers and acknowledge and agree to indemnify, defend, and hold harmless Utsavlife, its licensors, their affiliates, and their respective officers, directors, employees, and agents from any loss arising out of or related to the use of the Platform or any Bookings made through the Platform. This obligation will survive your use of the Platform and termination of your Agreement with us. For purposes of the Platform Terms, “Loss” means all losses, liabilities, damages, awards, settlements, claims, suits, proceedings, costs, and expenses (including reasonable legal prices and disbursements and costs of investigation, litigation, settlement, judgment, interest, and penalties). Utsavlife shall not be liable to you for any claims arising out of any act or omission on the part of the Third-Party Service Provider(s) including, but not limited to, any lost, stolen, or incorrectly processed payments. Utsavlife expressly disclaims any responsibility and liability for all services provided by the Third-Party Service Provider(s).</p>
      <p class="modal-para">k. Please note that all Booking payments are collected by Utsavlife only through the Platform and not through any third parties (except Third-Party Service Provider(s)). We do not usually authorize any third party (except Third-Party Service Provider(s)) to collect monies on our behalf; however, if we have authorized any third party then such third party will have received a written authorization from Utsavlife either by way of any agreement or an authorization letter. Kindly verify with such a third party before you make any payments to them, alternatively, you can always check with us by writing to us at the email address provided under the ‘Contact for User Support/Queries’ section below.</p>
      <p class="modal-para">l. Further, Utsavlife is solely authorized to offer discounts / offers, if any, on the Booking prices. These discounts / offers are communicated on the Platform or via direct communication to you from Utsavlife via email, SMS, phone, or such other means of communication, and can be availed only through the Platform, unless otherwise specifically communicated by Utsavlife. Other than Utsavlife, no person, including without limitation, Service providers or any third-party platform, are allowed to offer any discounts on the Booking prices offered on the Platform. Utsavlife shall not be liable for any claims arising from such unauthorized discounts / offers offered by any person (including any third- party platform or Service Provider), other than Utsavlife.</p>
      <p class="modal-para"><b>2. Cancellation and Refund Policy:</b></p>
      <p class="modal-para">You may cancel your booked service through your account on the Platform. However, please note that the cancellation will become effective at the end of the then-current billing period; in other words, we will not renew your booked Service, but the existing Booked service  will continue until the end of its billing period and there shall be no refund of the price already paid for the same, unless otherwise specified in the Refund Policy. So, please read these terms and conditions and the <a href="#" data-bs-toggle="modal" data-bs-target="#refund" data-bs-dismiss="modal">Refund Policy</a> carefully before purchasing any Service.</p>
      <p class="modal-para">When you cancel your Booking, Utsavlife may disable access to features made available to you upon your Booked service, while your account may continue to exist on the Platform.</p>
      <h4 class="modal-heading" id="use_of_platform2">F. Use of the Platform</h4>
      <p class="modal-para">Subject to the Platform Terms, Utsavlife hereby grants you a non- exclusive, non-transferable, non-sublicensable, limited license to access and use the Utsavlife Platform for your own personal, non-commercial and private use on an ‘as is’ basis in accordance with these Terms and Conditions and other Platform Terms.</p>
      <p class="modal-para">Subject to payment of the Booking price, and your compliance (as a customer) with all Platform Terms, Utsavlife and the Service providers grant you (as a customer) a non- exclusive, non-transferable, non-sublicensable, limited license, during the applicable Booking Period, to access and view the Service, non-commercial, private use only, in accordance with the Platform Terms. </p>
      <p class="modal-para">If you are a Service Provider, Utsavlife grants you a limited, non-exclusive, non- transferable, non-sublicensable license to access and use the Platform for Your own personal and commercial use in accordance with these Platform Terms and any other agreement(s) that may be executed between you (as a Service Provider) and Utsavlife (as applicable). Except as expressly permitted by Utsavlife under these Platform Terms or otherwise in writing to you, you will not reproduce, duplicate, copy, sell, redistribute, create derivative works or otherwise exploit the Platform or any portion of the Platform (including but not limited to any copyrighted material, trademarks, or other proprietary information).</p>
      <p class="modal-para">Except as expressly permitted under any of the Platform Terms or otherwise in writing, you will not reproduce, duplicate, copy, sell, redistribute, create derivative works or otherwise exploit the Platform or any portion of the Platform (including but not limited to any copyrighted material, trademarks, or other proprietary information).</p>
      <h4 class="modal-heading" id="content_conduct">G. Service and Conduct</h4>
      <p class="modal-para">1. As a User, you may submit User-generated Service (as defined under the ‘Intellectual Property’ section below) on the Platform. However, you must understand that Utsavlife does not guarantee any confidentiality with respect to any User-generated Service you submit.</p>
      <p class="modal-para">2. You shall be solely responsible for your own User-generated Service and the consequences of submitting and publishing such Service on the Platform. You affirm, represent, and warrant that you own or have the necessary licenses, rights, consents, and permissions to publish the User-generated Service that you submit. You further agree that User-generated Service you submit on the Utsavlife Platform will not contain third party copyrighted material, or material that is subject to other third-party proprietary rights, unless you have permission from the rightful owner of the material, or you are otherwise legally entitled to post the material and to grant Utsavlife the necessary license and rights required under the Platform Terms. You shall solely be responsible for all claims in respect of your User-generated Service published on the Platform.</p>
      <p class="modal-para">3. For clarity, you retain your ownership rights in your User-generated Service. However, you grant a limited license to Utsavlife to make available the User-generated Service on the Platform. Please read the ‘Intellectual Property’ section below to know the exact nature of license and rights you grant to Utsavlife.</p>
      <p class="modal-para">4. Furthermore, you confirm that you shall not host, display, upload, modify, publish, transmit, store, update or share User-generated Service or any information on the Platform that:</p>
      <p class="modal-para">a. belongs to another person and to which you do not have any right;</p>
      <p class="modal-para">b. is defamatory, obscene, pornographic, invasive of another’s privacy including bodily privacy, insulting or harassing on the basis of gender, libellous, racially or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with or contrary to the laws in force;</p>
      <p class="modal-para">c. is harmful to a child;</p>
      <p class="modal-para">d. infringes any patent, trademark, copyright or other proprietary rights of another;</p>
      <p class="modal-para">e. violates any law, statue, ordinance or regulation or Platform Terms;</p>
      <p class="modal-para">f. deceives or misleads any User about the origin of the message or knowingly and intentionally communicates any information which is patently false or misleading in nature but may reasonably be perceived as a fact;</p>
      <p class="modal-para">g. impersonates another person;</p>
      <p class="modal-para">h. threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting other nation;</p>
      <p class="modal-para">i. contains software virus or any other computer code, file or program designed to interrupt, destroy or limit the functionality of any computer resource;</p>
      <p class="modal-para">j. is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person;</p>
      <p class="modal-para">k. False, inaccurate or misleading;</p>
      <p class="modal-para">l. obscene or contain pornography;</p>
      <p class="modal-para">m. Contain any viruses, trojan horses, worms, cancelbots or other computer programming routines that may damage, detrimentally interfere with, surreptitiously intercept, or expropriate any system, data or Personal Information.</p>
      <p class="modal-para">5. Your conduct on the Platform shall strictly be in accordance with the User Guidelines and other Platform Terms.</p>
      <p class="modal-para">6. You understand that as a User you may interact with Minors/Children (refer to ‘Right to Access and Account Creation’ section above) on the Platform; accordingly, you shall make yourself fully aware of our <a href="#" data-bs-toggle="modal" data-bs-target="#minor_inter" data-bs-dismiss="modal">Minor & Customer Interaction Guidelines</a> and conduct yourself in accordance thereof.</p>
      <p class="modal-para">7. You understand and confirm that you shall not during your use of the Utsavlife Platform at any time post or publish any Service, comments or act in any way which will amount to harassment of any other User. If at any given point it comes to Utsavlife’s notice that you have engaged in any kind of harassment of other Users, then in such a case you agree that Utsavlife shall have the sole right to suspend/terminate your account with immediate effect and without any notice of such suspension or termination and we also reserve the right in our sole discretion to initiate any legal proceedings against you in such cases.</p>
      <p class="modal-para">8. Utsavlife does not endorse any User-generated Service submitted on the Utsavlife Platform by any User, or any opinion, recommendation, or advice expressed therein, and Utsavlife expressly disclaims any and all liability in connection with User-generated Service. Utsavlife does not permit copyright infringing activities and infringement of intellectual property rights on the Utsavlife Platform, and Utsavlife will remove all User-generated Service if properly notified that such User-generated Service infringes on another’s intellectual property rights in line with its obligations as an ‘intermediary’. Utsavlife reserves the right to remove User- generated Service without prior notice if it has reason to believe that the User- generated Service is violative of these Terms and Conditions. Please refer to the <a href="#" data-bs-toggle="modal" data-bs-target="#takedown" data-bs-dismiss="modal">Takedown Policy</a> and ‘Copyright, Trademarks and other Intellectual Property Rights ‘section below to understand the process to notify Utsavlife about any infringing Service and the process of takedown of infringing Service followed by Utsavlife.</p>
      <p class="modal-para">9. You shall not engage in any activity that increases/optimizes the User views on any particular Service Provider; these activities, without limitation, include creating multiple fake accounts as Customers, either by yourself or through a third-party.</p>
      <p class="modal-para">10. You shall not engage in any activity that will negatively impact Utsavlife and/or other Users of the Platform, including without limitation, activities that involve screen- recording, screen-casting or downloading on any other device of any Service Provider Service (live or recorded) in any manner that is not directly facilitated as feature within the Platform and/or sharing or otherwise publishing such screen-recorded Service on third-party platforms, either for a cost or otherwise. If Utsavlife becomes aware of your engagement, either by yourself or through a third-party, in any such activity, then Utsavlife may immediately terminate your or such User’s access / Booking along with termination and removal of access to all downloaded Service with a right to initiate appropriate legal action, at the sole discretion of Utsavlife.</p>
      <h4 class="modal-heading" id="communications">H. Communications</h4>
      <p class="modal-para">When you visit the Platform, you are communicating with us electronically. You may be required to provide a valid phone number while creating any account with us or while enrolling or purchasing any Service. We may communicate with you by e- mail, SMS, phone call or by posting notices on the Platform or by any other mode of communication. By providing your information you authorize Utsavlife, its affiliates, and their respective employees, agents, and contractors to initiate electronic communications by email, telephone calls, or such other mode of communication with respect to your use of the Platform and regarding the products and services offered by Utsavlife and its affiliates. These communications may be made by or on behalf of Utsavlife, even if your phone number is registered on any state or federal do not call list. Telephone calls may be recorded. You acknowledge that your telephone operator and/or internet service provider may have levied certain charges on you vis-à-vis your communications with Utsavlife as it constitutes availing their services, and you agree to be responsible for all such charges, and Utsavlife will not be responsible for any such charges. Do not submit your information if you do not consent to being contacted by telephone, text, email or such other mode of communication. Further, you will always have an option to unsubscribe / opt out from any promotional communications sent by Utsavlife and / or its affiliates either by following the relevant instructions that may be communicated via text, email or such other mode of communication in which you received a promotional communication or by disabling the options provided within your account on the Platform.</p>
      <p class="modal-para">Please note that –</p>
      <p class="modal-para">1. If you opt out of promotional communications, we may still send you transactional communications, such as service announcements, administrative and legal notices, and information about your account, without offering you the opportunity to opt out of these communications. If you no longer wish to use our Platform or receive any communications from us (except for those that are legally required), then you may delete your account by either writing to us at the email address provided under ‘Contact for User Support/Queries ‘section below by using the option enabled within the Platform; and</p>
      <p class="modal-para">2. opting out of promotional communications only affects future communications from us. If we have already provided your information to a third party (as stated in our Privacy Policy) before you changed your preferences or updated your information, you may have to change your preferences directly with that third party.</p>
      <p class="modal-para">3. We do not sell your Personal Information to third parties, and we do not use your name or name of your company in marketing statements without your consent.</p>
      <p class="modal-para">Further, in respect of interactions between Users - Utsavlife is only an intermediary and does not monitor any of the interactions that take place between Users on the Platform, but Utsavlife has clearly laid out the terms and guidelines a User must follow in their conduct on the Platform as part of the Platform Terms; and if Utsavlife receives from any User a complaint of misconduct against you, in any form, or if Utsavlife otherwise deems necessary, Utsavlife reserves the right to suspend or terminate your access to any the Platform or any part thereof at any time, with or without giving any notice or reason.</p>
      <p class="modal-para">You acknowledge that any User-generated Service (including without limitation any Service Provider Service, chats, postings, or materials posted by the Users) posted by you on part of the Platform, is neither endorsed nor controlled by us. You further understand and agree that you shall be solely responsible for any User-generated Service published by you on the Platform, including its legality, reliability, accuracy, and appropriateness, and shall be solely liable for the consequences of its publication. You represent and warrant that you own and control all rights in and to any User-generated Service uploaded by you on the Platform, or that you have the necessary licenses or permissions or are legally entitled to use and reproduce such User-generated Service on the Platform.</p>
      <h4 class="modal-heading" id="processing_personal_information">I. Processing of Personal Information</h4>
      <p class="modal-para">All our collection, processing, sharing and storing of any Personal Information collected from you shall be in accordance with our Privacy Policy. Kindly read the same to understand the security measures undertaken by Utsavlife to safeguard your Personal Information. Should you have any queries in respect of the same, please feel free to write to us at <a href="mailto:info@utsavlife.com">info@utsavlife.com</a>.</p>
      <h4 class="modal-heading" id="intellectual_property_license">J. Intellectual Property and License to User-generated Service</h4>
      <p class="modal-para"><b>1. User-generated Service:</b> You shall remain the sole owner of any Service uploaded or published or submitted or posted by you on the Platform, including without limitation, the Service published by you as a Service Provider and/or any text, image, media, written statements or other Service posted or published by a User anywhere on the Platform including without limitations in the comments section (“User-generated Service”)and Utsavlife does not claim any ownership over any User-generated Service uploaded/published by any User on the Platform.</p>
      <p class="modal-para">By submitting the User-generated Service on the Platform, you hereby grant Utsavlife a limited, worldwide, non-exclusive, royalty-free, sub-licensable and transferable license to use, reproduce, distribute, share, display, publish, retain, make available online and/or electronically transmit such User-generated Service as well as technical information collected via the Platform to the extent necessary (i) to provide the Platform and our Services; (ii) to perform our obligations under the Platform Terms and other written agreement with the User; (iii) to provide, monitor, correct, and improve the Platform and Services related thereto; (iv) for the Utsavlife Platform and Utsavlife’s (and its successors’, subsidiaries and affiliates’) business, including without limitation for promoting and redistributing part or all of the Utsavlife Platform in any media formats and through any media channels; (v) to de-identify User data such that there is no reasonable basis to believe that the information can be used, alone, or in combination with other reasonably available information, to identify any individual or to identify User as the source of such data; (vi) to aggregate User data with other data; and (vii) to comply with applicable laws. However, please note that we will never disclose aggregated or de-identified information in a manner that could identify you as an individual, and all your information shall be processed in accordance with our Privacy Policy.</p>
      <p class="modal-para">You also hereby grant each User of the Platform a limited, non-exclusive license to access your User-generated Service through the Platform.</p>
      <p class="modal-para"><b>2. Utsavlife Service:</b> Utsavlife and / or its affiliates own all information and materials (in whatever form or media) provided or communicated to you by or on behalf of Utsavlife including but not limited to, the Platform, illustrations, letters, images, ideas, concepts, the layout, design, flow, look and price of the Platform, logos, marks, graphics, audio files, video files, any software which is owned by or licensed to Utsavlife and / or its affiliates, the underlying source and object code, instructions embedded in any form of digital documents and other data, information, or material made available to you by Utsavlife (“Utsavlife Service”). Utsavlife Service specifically excludes any Service uploaded by the Users, including without limitation, any User-generated Service on the Platform. Utsavlife Service, including its trademarks, will not be used, modified, or altered by you in any way. You acknowledge and agree that you do not acquire any ownership or rights to the Utsavlife Service or the Platform by use of the Platform. You acknowledge and agree that the Utsavlife Service is protected by the copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws and any unauthorized use, reproduction, modification, distribution, transmission, republication, display or performance of the Utsavlife Service and any component thereof is strictly prohibited.</p>
      <p class="modal-para">You confirm and undertake not to utilize any data mining tools, robots, or similar data gathering and extraction tools to extract for re-utilization of any substantial parts of this Platform, without Utsavlife’s express prior written consent.</p>
      <h4 class="modal-heading" id="feedback">K. Priced-back</h4>
      <p class="modal-para">If any User(s) submits suggestions, ideas, comments, or questions containing product priced-back about the Platform or any of the Services, either through the Platform or otherwise (“Priced-back”), then such User(s) grants Utsavlife and its affiliates a worldwide, non-exclusive, royalty-free, perpetual, and irrevocable right to use (and full right to sublicense), reproduce, modify, adapt, publish, translate, create derivative works from, distribute, transmit, and display such Pricedback in any form. Users shall have no intellectual property right in the Platform as a result of Utsavlife’s incorporation of their Priced-back in the Platform.</p>
      <h4 class="modal-heading" id="copyrights">L. Copyright, Trademarks, and other Intellectual Property Rights</h4>
      <p class="modal-para">At Utsavlife, we respect the intellectual property of others just as much ours and, hence, if you believe that your intellectual property rights have been used in a way that gives rise to concerns of infringement of your intellectual property (including your copyrights and trademarks), then kindly write to us at <a href="mailto:info@utsavlife.com">info@utsavlife.com</a> with complete details as required under <a href="#" data-bs-toggle="modal" data-bs-target="#takedown" data-bs-dismiss="modal">Takedown Policy</a>. If Utsavlife has knowledge of or has any reason to believe that any User-generated Service on the Platform violates the intellectual property rights of Utsavlife or other Users, then we reserve the right to remove access to such Service in accordance with takedown practices specified in <a href="#" data-bs-toggle="modal" data-bs-target="#takedown" data-bs-dismiss="modal">Takedown Policy</a>.</p>
      <p class="modal-para">If Utsavlife has knowledge of or has any reason to believe that any User-generated Service on the Platform violates the intellectual property rights of Utsavlife or other Users, then we reserve the right to remove access to such Service in accordance with takedown practices specified in <a href="#" data-bs-toggle="modal" data-bs-target="#takedown" data-bs-dismiss="modal">Takedown Policy.</a></p>
      <h4 class="modal-heading" id="claims_against_user_content">M. Claims Against User-generated Service</h4>
      <p class="modal-para">Utsavlife does not monitor or have any control over or does not warrant, and makes no claim or representation regarding the accuracy, completeness, or usefulness of any User-generated Service provided on the Platform by its Users and accepts no responsibility for reviewing changes or updates to, or the quality, Service, policies, nature or reliability of, such User-generated Service. Utsavlife disclaims all liability and responsibility arising from any reliance placed on such materials by you. All statements and/or opinions expressed in these materials, and all articles and responses to questions and other Service, other than the Utsavlife Service, are solely the responsibility of the User providing those materials.</p>
      <h4 class="modal-heading" id="unacademy_rights">N. Utsavlife’s Rights</h4>
      <p class="modal-para">In respect of the entire Platform, Utsavlife reserves the following rights:</p>
      <p class="modal-para">1. Utsavlife reserves the right to put on-hold or reject or suspend or terminate your registration on the Platform for the purpose of complying with the legal and regulatory requirements.</p>
      <p class="modal-para">2. Utsavlife reserves the right to remove you and/or the User-generated Service without notice if you violate any provisions of the Platform Terms.</p>
      <p class="modal-para">3. Utsavlife may modify, terminate, or refuse to provide Services at any time for any reason, without notice.</p>
      <p class="modal-para">4. Notwithstanding anything contrary stated in the Platform Terms, in its sole discretion, Utsavlife may remove anyone from the Platform at any time for any reason.</p>
      <p class="modal-para">5. Utsavlife reserves the right to access your account and/or the User-generated Service in order to respond to requests for technical support, to maintain the safety and security of the Platform, legal purposes and for other legitimate business purposes, as necessary, in Utsavlife’s discretion.</p>
      <p class="modal-para">6. Utsavlife has no obligation to monitor any Service that appears on the Platform or review any conduct occurring through the Platform, including any interactions between Users, however, if Utsavlife receives notice or becomes aware of, any violation of the Platform Terms, then, Utsavlife reserves the right to refuse your access to the Platform, terminate accounts or remove such violating Service at any time without notice to you.</p>
      <h4 class="modal-heading" id="platform_availability">O. Platform Availability</h4>
      <p class="modal-para">Your access to the Platform may occasionally be suspended or restricted to allow for repairs, maintenance, or due to the introduction of new facilities or services at any time without prior notice. We will attempt to limit the frequency and duration of any such suspension or restriction. You agree that Utsavlife will not be liable for any losses that may be incurred by you if for any reason all or part of the Platform is unavailable at any time or for any period for use.</p>
      <h4 class="modal-heading" id="deletion_of_account">P. Deletion of Account</h4>
      <p class="modal-para">As a Customer, you may delete your account at any time by either writing to us at the email address provided under ‘Contact for User Support/Queries’ section below or by using the delete option provided within your account on the Platform (if available). If your account is deleted (regardless of the reason), you will no longer have access to your account on the Platform and your User-generated Service may no longer be available; any deletion once processed is irrecoverable. Utsavlife is not responsible for the loss of your information and/or User-generated Service upon deletion and Utsavlife shall not be liable to any party in any way for the inability to access User-generated Service arising from any deletion. Please note that all accounts will remain active unless you explicitly ask us to delete it, and applicable Booking payments shall continue to be deducted until cancelled by you or until your account is deleted on your request (as stated in the ‘Pricing and Payments’ section above) or otherwise terminated in accordance with the Platform Terms</p>
      <p class="modal-para">Please note that we may not be able to delete all communications or photos, files, or other documents publicly made available by you on the Platform, however, we shall anonymize your Personal Information (as defined in the Privacy Policy) in such a way that you can no longer be identified as an individual in association with such information made available by you on the Platform. We will never disclose aggregated or de-identified information in a manner that could identify you as an individual.</p>
      <p class="modal-para">If you are a Service Provider, your access and use of the Platform may be subject to a separate agreement with Utsavlife and shall be collectively governed by the terms of such agreement, the Terms and Conditions and other Platform Terms.</p>
      <h4 class="modal-heading" id="disclaimer">Q. Disclaimer:</h4>
      <p class="modal-para">YOU AGREE THAT THE PLATFORM, SERVICE, AND ALL MATERIALS ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS AND YOUR USE OF THE PLATFORM SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, UTSAVLIFE, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM AND EXCLUDE ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE PLATFORM AND YOUR USE THEREOF. TO THE FULLEST EXTENT PERMITTED BY LAW, UTSAVLIFE EXCLUDES ALL WARRANTIES, CONDITIONS, TERMS OR REPRESENTATIONS ABOUT THE ACCURACY, SECURITY, RELIABILITY, QUALITY, AVAILABILITY OR COMPLETENESS OF THE PLATFORM, USER-GENERATED SERVICE ON THE PLATFORM, OR THE SERVICE OF ANY SITES SO LINKED AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF USER-GENERATED SERVICE OR ANY SERVICE ON THE PLATFORM, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE PLATFORM, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE PLATFORM, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE PLATFORM BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY USER-GENERATED SERVICE OR ANY OTHER SERVICE OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY USER- GENERATED SERVICE OR ANY OTHER SERVICE THAT IS POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE PLATFORM AS UTSAVLIFE IS STRICTLY AN INTERMEDIARY AS UNDER THE INFORMATION TECHNOLOGY ACT, 2000. UTSAVLIFE DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY USER- GENERATED SERVICE OR THE PLATFORM ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE PLATFORM OR ANY HYPERLINKED SERVICES OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND UTSAVLIFE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF USER-GENERATED SERVICE OR SERVICES. AS WITH THE BOOKING OF A SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>
      <h4 class="modal-heading" id="limitation_of_liability">R. Limitation of Liability</h4>
      <p class="modal-para">TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL UTSAVLIFE, ITS AFFILIATES, THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, LOSSES OR EXPENSES OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF USER-GENERATED SERVICE OR ANY OTHER SERVICE AVAILABLE AT UTSAVLIFE, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR UTSAVLIFE PLATFORMS, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE UTSAVLIFE PLATFORM, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR UTSAVLIFE PLATFORMS BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY USER-GENERATED SERVICE OR ANY OTHER SERVICE OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY SERVICE POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE UTSAVLIFE PLATFORM, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT UTSAVLIFE IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
      <p class="modal-para">WE UNDERSTAND THAT, IN SOME JURISDICTIONS, WARRANTIES, DISCLAIMERS AND CONDITIONS MAY APPLY THAT CANNOT BE LEGALLY EXCLUDED, IF THAT IS TRUE IN YOUR JURISDICTION, THEN TO THE EXTENT PERMITTED BY LAW, UTSAVLIFE AND ITS AFFILIATES LIMIT THEIR LIABILITY FOR ANY CLAIMS UNDER THOSE WARRANTIES OR CONDITIONS TO SUPPLYING YOU THE UTSAVLIFE PLATFORM AGAIN.</p>
      <p class="modal-para">YOU SPECIFICALLY ACKNOWLEDGE THAT UTSAVLIFE SHALL NOT BE LIABLE FOR USER- GENERATED SERVICE OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU.</p>
      <p class="modal-para">THE UTSAVLIFE PLATFORM IS CONTROLLED AND OFFERED BY UTSAVLIFE AND / OR ITS AFFILIATES DEPENDING UPON YOUR JURISDICTION. UTSAVLIFE MAKES NO REPRESENTATIONS THAT THE UTSAVLIFE PLATFORM IS APPROPRIATE OR AVAILABLE FOR USE IN OTHER LOCATIONS. THOSE WHO ACCESS OR USE THE UTSAVLIFE PLATFORM FROM OTHER JURISDICTIONS DO SO AT THEIR OWN VOLITION AND ARE RESPONSIBLE FOR COMPLIANCE WITH LOCAL LAW.</p>
      <h4 class="modal-heading" id="indemnity_and_release">S. Indemnity and Release</h4>
      <p class="modal-para">To the extent permitted by applicable law, you agree to defend, indemnify and hold harmless Utsavlife, its affiliates, their respective officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s prices) arising from: (i) your use of and access to the Utsavlife Platform; (ii) your violation of any term of the Platform Terms; (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right; (iv) any claim that your User-generated Service caused damage to a third party; or (v) violation of any applicable laws. This defence and indemnification obligation will survive these Terms and Conditions and your use of the Utsavlife Platform.</p>
      <p class="modal-para">You hereby expressly release Utsavlife, its affiliates and any of their respective officers, directors, employees and agents from any cost, damage, liability or other consequence of any of the actions/inactions of any third-party vendors or service providers and specifically waive any claims or demands that you may have in this behalf against any of Utsavlife, its affiliates and any of their respective officers, directors, employees and agents under any statute, contract or otherwise</p>
      <h4 class="modal-heading" id="governing_laws">T. Applicable Law and Jurisdiction</h4>
      <p class="modal-para">The applicable law and jurisdiction is dependent upon which entity forming part of the Utsavlife group is offering you the Platform and the Services, which in turn is dependent upon the Booking chosen by you. Illustratively, Services provisioned in respect of Bookings pertaining to India, Utsavlife India shall be the entity rendering the Services and, accordingly, the Agreement shall be governed by and construed in accordance with the laws of India; and you agree, as we do, to submit to the exclusive jurisdiction of the courts at Bangalore, Karnataka, India. Similarly, Services in respect of Bookings pertaining to US shall be rendered by Utsavlife Inc. and, accordingly, in such cases, the Agreement shall be governed by and construed in accordance with the laws of State of Delaware, U.S.A. and you agree, as we do, to submit to the exclusive jurisdiction of the courts at State of Delaware, U.S.A.</p>
      <h4 class="modal-heading" id="general_provisions">U. General Provisions:</h4>
      <p class="modal-para"><b>1. Legal Notices:</b> In the event of any other disputes or claims arising from the use of the Utsavlife Platform, please get in touch with us at <a href="mailto:info@utsavlife.com">info@utsavlife.com</a> </p>
      <p class="modal-para"><b>2. Modification, Amendment or Termination:</b> Utsavlife may, in its sole discretion, modify or revise the Agreement and policies at any time, and you agree to be bound by such modifications or revisions. Your continued use of the Platform post any modification of the Agreement shall be taken as your consent and acceptance to such modifications. Nothing in the Agreement shall be deemed to confer any third-party rights or benefits. You are advised to check our Platform frequently to see recent changes and to keep yourself updated with the most recent updates.</p>
      <p class="modal-para"><b>3. Force Majeure:</b> Utsavlife shall not be liable for failure to perform, or the delay in performance of, any of its obligations if, and to the extent that, such failure or delay is caused by events substantially beyond its control, including but not limited to acts of God, acts of the public enemy or governmental body in its sovereign or contractual capacity, war, terrorism, floods, fire, strikes, epidemics, civil unrest or riots, power outage, and/or unusually severe weather.</p>
      <p class="modal-para"><b>4. Miscellaneous:</b> If any part of the Agreement is found to be unlawful, void or unenforceable, that part of the Agreement will be deemed severable and will not affect the validity and enforceability of any remaining provisions. Any notice required to be given in connection with the Platform shall be in writing and sent to the registered office of Utsavlife. We do not guarantee continuous, uninterrupted or secure access to the Platform, and operation of the Platform may be interfered by numerous factors outside our control. Headings are for reference purpose only and in no way define, limit, construe or describe the scope or extent of such section. Our failure to act with respect to any breach by you or others does not waive our right to act with respect to subsequent or similar breaches.</p>
      <h4 class="modal-heading" id="user_support">V. Contact for User Support/Queries</h4>
      <p class="modal-para">For queries relating to Services offered by Utsavlife, please write to us at <a href="mailto:info@utsavlife.com">info@utsavlife.com</a></p>
      <h4 class="modal-heading" id="contact_us">W. Contact Us</h4>
      <p class="modal-para">If you have concerns or queries regarding the Platform Terms, you may write to us by email at <a href="mailto:info@utsavlife.com">info@utsavlife.com</a> or by post to:</p>
      <p class="modal-para"><b>Utsavlife Private Limited</b></p>
      <p class="modal-para">R- 16, Uttam Nagar west metro station Gate Number 1,</p>
      <p class="modal-para">Metro pillar Number 690, Bikaner vali Gali, New Delhi 110059, India.</p>
      <h4 class="modal-heading">Annexure A</h4>
      <p class="modal-para">All Services offered on the Platform other than those offered under the ‘International Goals’ section on the Platform are provisioned by Utsavlife Private Limited (Utsavlife India), R- 16, Uttam Nagar west metro station Gate Number 1, Metro pillar Number 690, Bikaner vali Gali, New Delhi, India 110059.</p>
      <p class="modal-para">Terms and Conditions – Version 1.0</p>
      <p class="modal-para">Last Updated on 16th JANUARY, 2023</p>
      </div>
    </div>
  </div>
</div>